// <auto-generated> - Template:DTO, Version:1.1, Id:58fa7ee2-89f7-41e6-85ed-8d4482653990
namespace CGH.QuikRide.DTO.QR
{
	public partial class ReservationRequestOption
	{
		public ReservationRequestOption()
		{
			InitializePartial();
		}

		public int ReservationRequestOptionId { get; set; } // Primary key
		public System.Guid ReservationRequestId { get; set; }
		public System.DateTime SuggestedPickupStart { get; set; }
		public System.DateTime SuggestedPickupEnd { get; set; }
		public System.DateTime EstimatedArrivalStart { get; set; }
		public System.DateTime EstimatedArrivalEnd { get; set; }
		public int Score { get; set; }
		public int DataVersion { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public string CreatedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
		public string ModifiedBy { get; set; }
		public bool IsDeleted { get; set; }
		// public virtual System.Collections.Generic.ICollection<Reservation> Reservations { get; set; } // Many to many mapping -- Excluded navigation property per configuration.


		partial void InitializePartial();

	}
}
