// <auto-generated> - Template:DTO, Version:1.1, Id:58fa7ee2-89f7-41e6-85ed-8d4482653990
namespace CGH.QuikRide.DTO.QR
{
	public partial class Ride
	{
		public Ride()
		{
			InitializePartial();
		}

		public System.Guid RideId { get; set; } // Primary key
		public System.DateTime? Start { get; set; }
		public double? StartLatitude { get; set; }
		public double? StartLongitude { get; set; }
		public System.DateTime? End { get; set; }
		public double? EndLatitude { get; set; }
		public double? EndLongitude { get; set; }
		public int VehicleId { get; set; }
		public int DriverId { get; set; }
		public int UserId { get; set; }
		public int? DurationInSeconds { get; set; }
		public int? GeoDistance { get; set; }
		public int DataVersion { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public string CreatedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
		public string ModifiedBy { get; set; }
		public bool IsDeleted { get; set; }
		public virtual System.Collections.Generic.ICollection<RidePosition> RidePositions { get; set; } // Many to many mapping
		public virtual Driver Driver { get; set; } 
		// public virtual User User { get; set; }  -- Excluded navigation property per configuration.
		public virtual Vehicle Vehicle { get; set; } 


		partial void InitializePartial();

	}
}
