// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CGH.QuikRide.Repository.Entities.QR
{

    // BarcodeType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class BarcodeType
    {
        public int BarcodeTypeId { get; set; } // BarcodeTypeId (Primary key)
        public string Code { get; set; } // Code (length: 50)
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child Barcodes where [Barcode].[BarcodeTypeId] point to this entity (FK_Barcode_BarcodeType)
        /// </summary>
        public System.Collections.Generic.ICollection<Barcode> Barcodes { get; set; } // Barcode.FK_Barcode_BarcodeType
        /// <summary>
        /// Child BarcodeTypeTranslations where [BarcodeTypeTranslation].[BarcodeTypeId] point to this entity (FK_BarcodeTypeTranslation_BarcodeType)
        /// </summary>
        public System.Collections.Generic.ICollection<BarcodeTypeTranslation> BarcodeTypeTranslations { get; set; } // BarcodeTypeTranslation.FK_BarcodeTypeTranslation_BarcodeType

        public BarcodeType()
        {
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            Barcodes = new System.Collections.Generic.List<Barcode>();
            BarcodeTypeTranslations = new System.Collections.Generic.List<BarcodeTypeTranslation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
