// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CGH.QuikRide.Repository.Entities.QR
{

    // BusRoute
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class BusRoute
    {
        public int BusRouteId { get; set; } // BusRouteId (Primary key)
        public int BusRouteNumber { get; set; } // BusRouteNumber
        public System.DateTime? InServiceSince { get; set; } // InServiceSince
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child BusRouteStops where [BusRouteStop].[BusRouteId] point to this entity (FK_BusRouteStop_BusRoute)
        /// </summary>
        public System.Collections.Generic.ICollection<BusRouteStop> BusRouteStops { get; set; } // BusRouteStop.FK_BusRouteStop_BusRoute
        /// <summary>
        /// Child BusRouteTranslations where [BusRouteTranslation].[BusRouteId] point to this entity (FK_BusRouteTranslation_BusRoute)
        /// </summary>
        public System.Collections.Generic.ICollection<BusRouteTranslation> BusRouteTranslations { get; set; } // BusRouteTranslation.FK_BusRouteTranslation_BusRoute
        /// <summary>
        /// Child VehicleBusRoutes where [Vehicle_BusRoute].[BusRouteId] point to this entity (FK_Vehicle_BusRoute_BusRoute)
        /// </summary>
        public System.Collections.Generic.ICollection<VehicleBusRoute> VehicleBusRoutes { get; set; } // Vehicle_BusRoute.FK_Vehicle_BusRoute_BusRoute

        public BusRoute()
        {
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            BusRouteStops = new System.Collections.Generic.List<BusRouteStop>();
            BusRouteTranslations = new System.Collections.Generic.List<BusRouteTranslation>();
            VehicleBusRoutes = new System.Collections.Generic.List<VehicleBusRoute>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
