// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CGH.QuikRide.Repository.Entities.QR
{

    // Reservation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Reservation
    {
        public System.Guid ReservationId { get; set; } // ReservationId (Primary key)
        public int UserId { get; set; } // UserId
        public System.Guid PickUpLocationId { get; set; } // PickUpLocationId
        public System.Guid DestinationLocationId { get; set; } // DestinationLocationId
        public int ReservationRequestOptionId { get; set; } // ReservationRequestOptionId
        public int ReservationStatusTypeId { get; set; } // ReservationStatusTypeId
        public int? ReservationCancellationReasonId { get; set; } // ReservationCancellationReasonId
        public int NumberOfAdults { get; set; } // NumberOfAdults
        public int NumberOfChildren { get; set; } // NumberOfChildren
        public int NumberOfBabies { get; set; } // NumberOfBabies
        public int NumberOfWheelchairs { get; set; } // NumberOfWheelchairs
        public int NumberOfBikes { get; set; } // NumberOfBikes
        public bool PersonalCareAttendantIncluded { get; set; } // PersonalCareAttendantIncluded
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child ReservationRequests where [ReservationRequest].[ReplacesReservationId] point to this entity (FK_ReservationRequest_Reservation)
        /// </summary>
        public System.Collections.Generic.ICollection<ReservationRequest> ReservationRequests { get; set; } // ReservationRequest.FK_ReservationRequest_Reservation

        // Foreign keys

        /// <summary>
        /// Parent Location pointed by [Reservation].([PickUpLocationId]) (FK_Reservation_Location)
        /// </summary>
        public Location Location { get; set; } // FK_Reservation_Location

        /// <summary>
        /// Parent ReservationCancellationReasonType pointed by [Reservation].([ReservationCancellationReasonId]) (FK_Reservation_ReservationCancellationReasonType)
        /// </summary>
        public ReservationCancellationReasonType ReservationCancellationReasonType { get; set; } // FK_Reservation_ReservationCancellationReasonType

        /// <summary>
        /// Parent ReservationRequestOption pointed by [Reservation].([ReservationRequestOptionId]) (FK_Reservation_ReservationRequestOption)
        /// </summary>
        public ReservationRequestOption ReservationRequestOption { get; set; } // FK_Reservation_ReservationRequestOption

        /// <summary>
        /// Parent User pointed by [Reservation].([UserId]) (FK_Reservation_Users)
        /// </summary>
        public User User { get; set; } // FK_Reservation_Users

        public Reservation()
        {
            NumberOfWheelchairs = 0;
            NumberOfBikes = 0;
            PersonalCareAttendantIncluded = false;
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            ReservationRequests = new System.Collections.Generic.List<ReservationRequest>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
