// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CGH.QuikRide.Repository.Entities.QR
{

    // ReservationRequest
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ReservationRequestConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ReservationRequest>
    {
        public ReservationRequestConfiguration()
            : this("dbo")
        {
        }

        public ReservationRequestConfiguration(string schema)
        {
            ToTable("ReservationRequest", schema);
            HasKey(x => x.ReservationRequestId);

            Property(x => x.ReservationRequestId).HasColumnName(@"ReservationRequestId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            Property(x => x.PickupLocationId).HasColumnName(@"PickupLocationId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.DestinationLocationId).HasColumnName(@"DestinationLocationId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.ReservationRequestStatusTypeId).HasColumnName(@"ReservationRequestStatusTypeId").HasColumnType("int").IsRequired();
            Property(x => x.ReservationRequestCancellationReasonTypeId).HasColumnName(@"ReservationRequestCancellationReasonTypeId").HasColumnType("int").IsOptional();
            Property(x => x.RequestedPickupStart).HasColumnName(@"RequestedPickupStart").HasColumnType("datetime2").IsOptional();
            Property(x => x.RequestedPickupEnd).HasColumnName(@"RequestedPickupEnd").HasColumnType("datetime2").IsOptional();
            Property(x => x.RequestedArrivalStart).HasColumnName(@"RequestedArrivalStart").HasColumnType("datetime2").IsOptional();
            Property(x => x.RequestedArrivalEnd).HasColumnName(@"RequestedArrivalEnd").HasColumnType("datetime2").IsOptional();
            Property(x => x.NumberOfAdults).HasColumnName(@"NumberOfAdults").HasColumnType("int").IsRequired();
            Property(x => x.NumberOfChildren).HasColumnName(@"NumberOfChildren").HasColumnType("int").IsRequired();
            Property(x => x.NumberOfBabies).HasColumnName(@"NumberOfBabies").HasColumnType("int").IsRequired();
            Property(x => x.NumberOfWheelchairs).HasColumnName(@"NumberOfWheelchairs").HasColumnType("int").IsOptional();
            Property(x => x.NumberOfBikes).HasColumnName(@"NumberOfBikes").HasColumnType("int").IsOptional();
            Property(x => x.PersonalCareAttendantIncluded).HasColumnName(@"PersonalCareAttendantIncluded").HasColumnType("bit").IsRequired();
            Property(x => x.PassengerRequiresAssistance).HasColumnName(@"PassengerRequiresAssistance").HasColumnType("bit").IsRequired();
            Property(x => x.ReservationId).HasColumnName(@"ReservationId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.ReplacesReservationId).HasColumnName(@"ReplacesReservationId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.DataVersion).HasColumnName(@"DataVersion").HasColumnType("int").IsRequired();
            Property(x => x.CreatedUtcDate).HasColumnName(@"CreatedUtcDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.ModifiedUtcDate).HasColumnName(@"ModifiedUtcDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasOptional(a => a.Reservation).WithMany(b => b.ReservationRequests).HasForeignKey(c => c.ReplacesReservationId).WillCascadeOnDelete(false); // FK_ReservationRequest_Reservation
            HasOptional(a => a.ReservationRequestCancellationReasonType).WithMany(b => b.ReservationRequests).HasForeignKey(c => c.ReservationRequestCancellationReasonTypeId).WillCascadeOnDelete(false); // FK_ReservationRequest_ReservationRequestCancellationReasonType
            HasRequired(a => a.DestinationLocation).WithMany(b => b.DestinationLocation).HasForeignKey(c => c.DestinationLocationId).WillCascadeOnDelete(false); // FK_ReservationRequest_DestinationLocation
            HasRequired(a => a.PickupLocation).WithMany(b => b.PickupLocation).HasForeignKey(c => c.PickupLocationId).WillCascadeOnDelete(false); // FK_ReservationRequest_PickupLocation
            HasRequired(a => a.ReservationRequestStatusType).WithMany(b => b.ReservationRequests).HasForeignKey(c => c.ReservationRequestStatusTypeId).WillCascadeOnDelete(false); // FK_ReservationRequest_ReservationRequestStatusType
            HasRequired(a => a.User).WithMany(b => b.ReservationRequests).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_ReservationRequest_Users
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
