// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CGH.QuikRide.Repository.Entities.QR
{

    // ReservationCancellationReasonTypeTranslation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ReservationCancellationReasonTypeTranslation
    {
        public int ReservationCancellationReasonTypeTranslationId { get; set; } // ReservationCancellationReasonTypeTranslationId (Primary key)
        public int ReservationCancellationReasonTypeId { get; set; } // ReservationCancellationReasonTypeId
        public int LanguageTypeId { get; set; } // LanguageTypeId
        public string Value { get; set; } // Value (length: 4000)
        public int DisplayPriority { get; set; } // DisplayPriority
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent LanguageType pointed by [ReservationCancellationReasonTypeTranslation].([LanguageTypeId]) (FK_ReservationCancellationReasonTypeTranslation_LanguageType)
        /// </summary>
        public LanguageType LanguageType { get; set; } // FK_ReservationCancellationReasonTypeTranslation_LanguageType

        /// <summary>
        /// Parent ReservationCancellationReasonType pointed by [ReservationCancellationReasonTypeTranslation].([ReservationCancellationReasonTypeId]) (FK_ReservationCancellationReasonTypeTranslation_ReservationCancellationReasonType)
        /// </summary>
        public ReservationCancellationReasonType ReservationCancellationReasonType { get; set; } // FK_ReservationCancellationReasonTypeTranslation_ReservationCancellationReasonType

        public ReservationCancellationReasonTypeTranslation()
        {
            DisplayPriority = 100;
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
