// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CGH.QuikRide.Repository.Entities.QR
{

    // Vehicle
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Vehicle
    {
        public int VehicleId { get; set; } // VehicleId (Primary key)
        public int VehicleTypeId { get; set; } // VehicleTypeId
        public int VehicleStatusTypeId { get; set; } // VehicleStatusTypeId
        public double? Latitude { get; set; } // Latitude
        public double? Longitude { get; set; } // Longitude
        public string Vin { get; set; } // VIN (length: 17)
        public string LicensePlateNumber { get; set; } // LicensePlateNumber (length: 10)
        public System.DateTime StartDateInService { get; set; } // StartDateInService
        public System.DateTime? EndDateInService { get; set; } // EndDateInService
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child Drivers where [Driver].[CurrentVehicleId] point to this entity (FK_Driver_Vehicle)
        /// </summary>
        public System.Collections.Generic.ICollection<Driver> Drivers { get; set; } // Driver.FK_Driver_Vehicle
        /// <summary>
        /// Child Rides where [Ride].[VehicleId] point to this entity (FK_Ride_Vehicle)
        /// </summary>
        public System.Collections.Generic.ICollection<Ride> Rides { get; set; } // Ride.FK_Ride_Vehicle
        /// <summary>
        /// Child VehicleVehicleFeatureTypes where [Vehicle_VehicleFeatureType].[VehicleId] point to this entity (FK_Vehicle_VehicleFeatureType_Vehicle)
        /// </summary>
        public System.Collections.Generic.ICollection<VehicleVehicleFeatureType> VehicleVehicleFeatureTypes { get; set; } // Vehicle_VehicleFeatureType.FK_Vehicle_VehicleFeatureType_Vehicle

        // Foreign keys

        /// <summary>
        /// Parent VehicleStatusType pointed by [Vehicle].([VehicleStatusTypeId]) (FK_Vehicle_VehicleStatusType)
        /// </summary>
        public VehicleStatusType VehicleStatusType { get; set; } // FK_Vehicle_VehicleStatusType

        /// <summary>
        /// Parent VehicleType pointed by [Vehicle].([VehicleTypeId]) (FK_Vehicle_VehicleType)
        /// </summary>
        public VehicleType VehicleType { get; set; } // FK_Vehicle_VehicleType

        public Vehicle()
        {
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            Drivers = new System.Collections.Generic.List<Driver>();
            Rides = new System.Collections.Generic.List<Ride>();
            VehicleVehicleFeatureTypes = new System.Collections.Generic.List<VehicleVehicleFeatureType>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
