// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using SQLite;

namespace CGH.QuikRide.Xam.ModelData.QR
{
	[Table("Location")]
	public partial class Location
	{
		public string AddressLine1 { get; set; }
		public string AddressLine2 { get; set; }
		public string City { get; set; }
		public string CreatedBy { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public int DataVersion { get; set; }
		public bool IsDeleted { get; set; }
		public double? Latitude { get; set; }

		[PrimaryKey]
		public System.Guid LocationId { get; set; }

		public int LocationTypeId { get; set; }
		public double? Longitude { get; set; }
		public string ModifiedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
		public string Name { get; set; }
		public string PostalCode { get; set; }
		public string State { get; set; }
	}
}
