// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using SQLite;

namespace CGH.QuikRide.Xam.ModelData.QR
{
	[Table("UserRewardAccountTransaction")]
	public partial class UserRewardAccountTransaction
	{
		public string CreatedBy { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public int DataVersion { get; set; }
		public bool IsDeleted { get; set; }
		public string Memo { get; set; }
		public string ModifiedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
		public System.Guid UserRewardAccountId { get; set; }

		[PrimaryKey]
		public System.Guid UserRewardAccountTransactionId { get; set; }

		public int UserRewardAccountTransactionTypeId { get; set; }
		public int? Value { get; set; }
	}
}
