// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.DTO.QR
{
	public static class DemoGenderTypeTranslation
	{
		public static int SampleGenderTypeTranslationId0000 = 420686628;
		public static int SampleGenderTypeTranslationId0100 = 1630040125;

		public static GenderTypeTranslation SampleGenderTypeTranslation00
		{
			get
			{
				return new GenderTypeTranslation()
				{
					GenderTypeTranslationId = SampleGenderTypeTranslationId0000,
					GenderTypeId = 0,
					LanguageTypeId = 0,
					Value = "SampleValue",
					DisplayPriority = 0,
					Description = "SampleDescription",
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static GenderTypeTranslation SampleGenderTypeTranslation01
		{
			get
			{
				return new GenderTypeTranslation()
				{
					GenderTypeTranslationId = SampleGenderTypeTranslationId0100,
					GenderTypeId = 0,
					LanguageTypeId = 0,
					Value = "SampleValue",
					DisplayPriority = 0,
					Description = "SampleDescription",
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
