// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.DTO.QR
{
	public static class DemoReservationRequestStatusTypeTranslation
	{
		public static int SampleReservationRequestStatusTypeTranslationId0000 = 2118648318;
		public static int SampleReservationRequestStatusTypeTranslationId0100 = 1698368196;

		public static ReservationRequestStatusTypeTranslation SampleReservationRequestStatusTypeTranslation00
		{
			get
			{
				return new ReservationRequestStatusTypeTranslation()
				{
					ReservationRequestStatusTypeTranslationId = SampleReservationRequestStatusTypeTranslationId0000,
					ReservationRequestStatusTypeId = 0,
					LanguageTypeId = 0,
					Value = "SampleValue",
					DisplayPriority = 0,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static ReservationRequestStatusTypeTranslation SampleReservationRequestStatusTypeTranslation01
		{
			get
			{
				return new ReservationRequestStatusTypeTranslation()
				{
					ReservationRequestStatusTypeTranslationId = SampleReservationRequestStatusTypeTranslationId0100,
					ReservationRequestStatusTypeId = 0,
					LanguageTypeId = 0,
					Value = "SampleValue",
					DisplayPriority = 0,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
