// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.DTO.QR
{
	public static class DemoReservation
	{
		public static System.Guid SampleReservationId0000 = Guid.Parse("9c112849-fd41-4cb8-8fa9-ed7d1c29d7bf");
		public static System.Guid SampleReservationId0100 = Guid.Parse("62d6ef0a-77ca-4756-85b4-cacb095a4072");

		public static Reservation SampleReservation00
		{
			get
			{
				return new Reservation()
				{
					ReservationId = SampleReservationId0100,
					UserId = 0,
					PickUpLocationId = Guid.Parse("7da4dfbc-409e-44d1-981b-6f96590e4b63"),
					DestinationLocationId = Guid.Parse("9189b7ab-a944-4802-8f95-e3884466ff34"),
					ReservationRequestOptionId = 0,
					ReservationStatusTypeId = 0,
					ReservationCancellationReasonId = 0,
					NumberOfAdults = 0,
					NumberOfChildren = 0,
					NumberOfBabies = 0,
					NumberOfWheelchairs = 0,
					NumberOfBikes = 0,
					PersonalCareAttendantIncluded = false,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static Reservation SampleReservation01
		{
			get
			{
				return new Reservation()
				{
					ReservationId = SampleReservationId0100,
					UserId = 0,
					PickUpLocationId = Guid.Parse("7bc7f579-7866-4bd3-b03a-7edf39064999"),
					DestinationLocationId = Guid.Parse("9aadddf6-85ac-4d09-bbe6-16b2e7c9d843"),
					ReservationRequestOptionId = 0,
					ReservationStatusTypeId = 0,
					ReservationCancellationReasonId = 0,
					NumberOfAdults = 0,
					NumberOfChildren = 0,
					NumberOfBabies = 0,
					NumberOfWheelchairs = 0,
					NumberOfBikes = 0,
					PersonalCareAttendantIncluded = false,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
