// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.DTO.QR
{
	public static class DemoReservationRequestOption
	{
		public static int SampleReservationRequestOptionId0000 = 994747593;
		public static int SampleReservationRequestOptionId0100 = 337052729;

		public static ReservationRequestOption SampleReservationRequestOption00
		{
			get
			{
				return new ReservationRequestOption()
				{
					ReservationRequestOptionId = SampleReservationRequestOptionId0100,
					ReservationRequestId = Guid.Parse("b77d2e85-4036-4280-8be9-89663abf6aa3"),
					SuggestedPickupStart = DateTime.Now,
					SuggestedPickupEnd = DateTime.Now,
					EstimatedArrivalStart = DateTime.Now,
					EstimatedArrivalEnd = DateTime.Now,
					Score = 0,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static ReservationRequestOption SampleReservationRequestOption01
		{
			get
			{
				return new ReservationRequestOption()
				{
					ReservationRequestOptionId = SampleReservationRequestOptionId0100,
					ReservationRequestId = Guid.Parse("6e95d38a-c1ab-44cf-b25c-0cfc3923357e"),
					SuggestedPickupStart = DateTime.Now,
					SuggestedPickupEnd = DateTime.Now,
					EstimatedArrivalStart = DateTime.Now,
					EstimatedArrivalEnd = DateTime.Now,
					Score = 0,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
