// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.DTO.QR
{
	public static class DemoReservationRequest
	{
		public static System.Guid SampleReservationRequestId0000 = Guid.Parse("c521ab9f-bf20-4123-a9bf-3fd821560218");
		public static System.Guid SampleReservationRequestId0100 = Guid.Parse("6fd3c280-0017-4578-8ca3-453a465da0a0");

		public static ReservationRequest SampleReservationRequest00
		{
			get
			{
				return new ReservationRequest()
				{
					ReservationRequestId = SampleReservationRequestId0100,
					UserId = 0,
					PickupLocationId = Guid.Parse("c46b795e-bda1-4cb0-a544-c42341a309da"),
					DestinationLocationId = Guid.Parse("3b35854d-c6d1-49a2-a6b6-95409b64fc7f"),
					ReservationRequestStatusTypeId = 0,
					ReservationRequestCancellationReasonTypeId = 0,
					RequestedPickupStart = DateTime.Now,
					RequestedPickupEnd = DateTime.Now,
					RequestedArrivalStart = DateTime.Now,
					RequestedArrivalEnd = DateTime.Now,
					NumberOfAdults = 0,
					NumberOfChildren = 0,
					NumberOfBabies = 0,
					NumberOfWheelchairs = 0,
					NumberOfBikes = 0,
					PersonalCareAttendantIncluded = false,
					PassengerRequiresAssistance = false,
					ReservationId = Guid.Parse("bd181d6a-1f9f-4bf2-ae03-8eeaf1d09a31"),
					ReplacesReservationId = Guid.Parse("e7095d77-87d0-4727-bec6-05129a7a1ab3"),
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static ReservationRequest SampleReservationRequest01
		{
			get
			{
				return new ReservationRequest()
				{
					ReservationRequestId = SampleReservationRequestId0100,
					UserId = 0,
					PickupLocationId = Guid.Parse("cef08ba8-27a1-4066-b5d4-6502407e6ab9"),
					DestinationLocationId = Guid.Parse("cbed5bac-e590-406b-aa1c-d142dcbbb30f"),
					ReservationRequestStatusTypeId = 0,
					ReservationRequestCancellationReasonTypeId = 0,
					RequestedPickupStart = DateTime.Now,
					RequestedPickupEnd = DateTime.Now,
					RequestedArrivalStart = DateTime.Now,
					RequestedArrivalEnd = DateTime.Now,
					NumberOfAdults = 0,
					NumberOfChildren = 0,
					NumberOfBabies = 0,
					NumberOfWheelchairs = 0,
					NumberOfBikes = 0,
					PersonalCareAttendantIncluded = false,
					PassengerRequiresAssistance = false,
					ReservationId = Guid.Parse("a529a937-e4d3-4ed3-85bc-634eafce1968"),
					ReplacesReservationId = Guid.Parse("d0088265-9649-4a12-96d1-a3d41ade7f1b"),
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
