// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.DTO.QR
{
	public static class DemoRidePosition
	{
		public static System.Guid SampleRidePositionId0000 = Guid.Parse("2d1c9518-20c8-48a9-9141-1e112cdfb31b");
		public static System.Guid SampleRidePositionId0100 = Guid.Parse("d4bcb1fb-f2df-411f-8f0a-ce7e9e52720d");

		public static RidePosition SampleRidePosition00
		{
			get
			{
				return new RidePosition()
				{
					RidePositionId = SampleRidePositionId0000,
					RideId = Guid.Parse("15ed163e-1d2d-4b43-9999-b6358cdc20b8"),
					Latitude = 0,
					Longitude = 0,
					Ts = DateTime.Now,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static RidePosition SampleRidePosition01
		{
			get
			{
				return new RidePosition()
				{
					RidePositionId = SampleRidePositionId0100,
					RideId = Guid.Parse("10447c06-cf54-4fcb-8572-05e7ab7377df"),
					Latitude = 0,
					Longitude = 0,
					Ts = DateTime.Now,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
