// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.DTO.QR
{
	public static class DemoVehicleFeatureType
	{
		public static int SampleVehicleFeatureTypeId0000 = 1669126361;
		public static int SampleVehicleFeatureTypeId0100 = 1766696267;

		public static VehicleFeatureType SampleVehicleFeatureType00
		{
			get
			{
				return new VehicleFeatureType()
				{
					VehicleFeatureTypeId = SampleVehicleFeatureTypeId0000,
					Code = "SampleCode",
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static VehicleFeatureType SampleVehicleFeatureType01
		{
			get
			{
				return new VehicleFeatureType()
				{
					VehicleFeatureTypeId = SampleVehicleFeatureTypeId0100,
					Code = "SampleCode",
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
