// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.DTO.QR
{
	public static class DemoVehicleVehicleFeatureType
	{
		public static int SampleVehicleVehicleFeatureTypeId0000 = DemoVehicle.SampleVehicleId0000;
		public static int SampleVehicleVehicleFeatureTypeId0001 = DemoVehicleFeatureType.SampleVehicleFeatureTypeId0000;
		public static int SampleVehicleVehicleFeatureTypeId0100 = DemoVehicle.SampleVehicleId0100;
		public static int SampleVehicleVehicleFeatureTypeId0101 = DemoVehicleFeatureType.SampleVehicleFeatureTypeId0100;

		public static VehicleVehicleFeatureType SampleVehicleVehicleFeatureType00
		{
			get
			{
				return new VehicleVehicleFeatureType()
				{
					VehicleId = SampleVehicleVehicleFeatureTypeId0000,
					VehicleFeatureTypeId = SampleVehicleVehicleFeatureTypeId0001,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static VehicleVehicleFeatureType SampleVehicleVehicleFeatureType01
		{
			get
			{
				return new VehicleVehicleFeatureType()
				{
					VehicleId = SampleVehicleVehicleFeatureTypeId0100,
					VehicleFeatureTypeId = SampleVehicleVehicleFeatureTypeId0101,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
