// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.DTO.QR
{
	public static class DemoReservationCancellationReasonType
	{
		public static int SampleReservationCancellationReasonTypeId0000 = 1612383455;
		public static int SampleReservationCancellationReasonTypeId0100 = 1440250086;

		public static ReservationCancellationReasonType SampleReservationCancellationReasonType00
		{
			get
			{
				return new ReservationCancellationReasonType()
				{
					ReservationCancellationReasonTypeId = SampleReservationCancellationReasonTypeId0100,
					LanguageTypeId = 0,
					Code = "SampleCode",
					DisplayText = "SampleDisplayText",
					DisplayPriority = 0,
					Description = "SampleDescription",
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static ReservationCancellationReasonType SampleReservationCancellationReasonType01
		{
			get
			{
				return new ReservationCancellationReasonType()
				{
					ReservationCancellationReasonTypeId = SampleReservationCancellationReasonTypeId0100,
					LanguageTypeId = 0,
					Code = "SampleCode",
					DisplayText = "SampleDisplayText",
					DisplayPriority = 0,
					Description = "SampleDescription",
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
