// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.DTO.QR
{
	public static class DemoUsersLocation
	{
		public static int SampleUsersLocationId0000 = 919448891;
		public static System.Guid SampleUsersLocationId0001 = Guid.Parse("db81a7b5-32bd-472e-858e-7d2149a0e177");
		public static int SampleUsersLocationId0100 = 1334945866;
		public static System.Guid SampleUsersLocationId0101 = Guid.Parse("ef4237a9-469a-4ac9-b3a7-94d686d7f4b6");

		public static UsersLocation SampleUsersLocation00
		{
			get
			{
				return new UsersLocation()
				{
					UserId = SampleUsersLocationId0100,
					LocationId = SampleUsersLocationId0101,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static UsersLocation SampleUsersLocation01
		{
			get
			{
				return new UsersLocation()
				{
					UserId = SampleUsersLocationId0100,
					LocationId = SampleUsersLocationId0101,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
