// <auto-generated> - Template:MapperSqliteModelDataToMvvmLightModelObject, Version:1.1, Id:ec39b410-017a-407f-be75-0cf4fd66efd2
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using objQR = CGH.QuikRide.Xam.ModelObj.QR;
using dataQR = CGH.QuikRide.Xam.ModelData.QR;

namespace CGH.QuikRide.Xam
{
	public static partial class ModelMapper
	{

		#region ModelObj to ModelData

		public static dataQR.Driver ToModelData(this objQR.Driver source)
		{
			return new dataQR.Driver()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				CurrentVehicleId = source.CurrentVehicleId,
				DataVersion = source.DataVersion,
				DriverId = source.DriverId,
				IsDeleted = source.IsDeleted,
				Latitude = source.Latitude,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				UserId = source.UserId,
			};
		}

		public static dataQR.Feedback ToModelData(this objQR.Feedback source)
		{
			return new dataQR.Feedback()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				Dispositioned = source.Dispositioned,
				DriverId = source.DriverId,
				FeedbackId = source.FeedbackId,
				FeedbackTypeId = source.FeedbackTypeId,
				IsDeleted = source.IsDeleted,
				Latitude = source.Latitude,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				Title = source.Title,
				UserId = source.UserId,
				VehicleId = source.VehicleId,
			};
		}

		public static dataQR.FeedbackType ToModelData(this objQR.FeedbackType source)
		{
			return new dataQR.FeedbackType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				FeedbackTypeId = source.FeedbackTypeId,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static dataQR.GenderType ToModelData(this objQR.GenderType source)
		{
			return new dataQR.GenderType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				GenderTypeId = source.GenderTypeId,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static dataQR.Holiday ToModelData(this objQR.Holiday source)
		{
			return new dataQR.Holiday()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Date = source.Date,
				DisplayText = source.DisplayText,
				HolidayId = source.HolidayId,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static dataQR.LanguageType ToModelData(this objQR.LanguageType source)
		{
			return new dataQR.LanguageType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageCultureIdentifier = source.LanguageCultureIdentifier,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				NativeName = source.NativeName,
				ThreeLetterIsoLanguageName = source.ThreeLetterIsoLanguageName,
				TwoLetterIsoLanguageName = source.TwoLetterIsoLanguageName,
			};
		}

		public static dataQR.Location ToModelData(this objQR.Location source)
		{
			return new dataQR.Location()
			{
				AddressLine1 = source.AddressLine1,
				AddressLine2 = source.AddressLine2,
				City = source.City,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				Latitude = source.Latitude,
				LocationId = source.LocationId,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				Name = source.Name,
				PostalCode = source.PostalCode,
				State = source.State,
			};
		}

		public static dataQR.NotificationType ToModelData(this objQR.NotificationType source)
		{
			return new dataQR.NotificationType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				NotificationTypeId = source.NotificationTypeId,
			};
		}

		public static dataQR.Reservation ToModelData(this objQR.Reservation source)
		{
			return new dataQR.Reservation()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				DestinationLocationId = source.DestinationLocationId,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				NumberOfAdults = source.NumberOfAdults,
				NumberOfBabies = source.NumberOfBabies,
				NumberOfBikes = source.NumberOfBikes,
				NumberOfChildren = source.NumberOfChildren,
				NumberOfWheelchairs = source.NumberOfWheelchairs,
				PersonalCareAttendantIncluded = source.PersonalCareAttendantIncluded,
				PickUpLocationId = source.PickUpLocationId,
				ReservationCancellationReasonId = source.ReservationCancellationReasonId,
				ReservationId = source.ReservationId,
				ReservationRequestOptionId = source.ReservationRequestOptionId,
				ReservationStatusTypeId = source.ReservationStatusTypeId,
				UserId = source.UserId,
			};
		}

		public static dataQR.ReservationCancellationReasonType ToModelData(this objQR.ReservationCancellationReasonType source)
		{
			return new dataQR.ReservationCancellationReasonType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ReservationCancellationReasonTypeId = source.ReservationCancellationReasonTypeId,
			};
		}

		public static dataQR.ReservationRequest ToModelData(this objQR.ReservationRequest source)
		{
			return new dataQR.ReservationRequest()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				DestinationLocationId = source.DestinationLocationId,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				NumberOfAdults = source.NumberOfAdults,
				NumberOfBabies = source.NumberOfBabies,
				NumberOfBikes = source.NumberOfBikes,
				NumberOfChildren = source.NumberOfChildren,
				NumberOfWheelchairs = source.NumberOfWheelchairs,
				PassengerRequiresAssistance = source.PassengerRequiresAssistance,
				PersonalCareAttendantIncluded = source.PersonalCareAttendantIncluded,
				PickupLocationId = source.PickupLocationId,
				ReplacesReservationId = source.ReplacesReservationId,
				RequestedArrivalEnd = source.RequestedArrivalEnd,
				RequestedArrivalStart = source.RequestedArrivalStart,
				RequestedPickupEnd = source.RequestedPickupEnd,
				RequestedPickupStart = source.RequestedPickupStart,
				ReservationId = source.ReservationId,
				ReservationRequestCancellationReasonTypeId = source.ReservationRequestCancellationReasonTypeId,
				ReservationRequestId = source.ReservationRequestId,
				ReservationRequestStatusTypeId = source.ReservationRequestStatusTypeId,
				UserId = source.UserId,
			};
		}

		public static dataQR.ReservationRequestCancellationReasonType ToModelData(this objQR.ReservationRequestCancellationReasonType source)
		{
			return new dataQR.ReservationRequestCancellationReasonType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ReservationRequestCancellationReasonTypeId = source.ReservationRequestCancellationReasonTypeId,
			};
		}

		public static dataQR.ReservationRequestOption ToModelData(this objQR.ReservationRequestOption source)
		{
			return new dataQR.ReservationRequestOption()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				EstimatedArrivalEnd = source.EstimatedArrivalEnd,
				EstimatedArrivalStart = source.EstimatedArrivalStart,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ReservationRequestId = source.ReservationRequestId,
				ReservationRequestOptionId = source.ReservationRequestOptionId,
				Score = source.Score,
				SuggestedPickupEnd = source.SuggestedPickupEnd,
				SuggestedPickupStart = source.SuggestedPickupStart,
			};
		}

		public static dataQR.ReservationRequestStatusType ToModelData(this objQR.ReservationRequestStatusType source)
		{
			return new dataQR.ReservationRequestStatusType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ReservationRequestStatusTypeId = source.ReservationRequestStatusTypeId,
			};
		}

		public static dataQR.ReservationStatusType ToModelData(this objQR.ReservationStatusType source)
		{
			return new dataQR.ReservationStatusType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ReservationStatusTypeId = source.ReservationStatusTypeId,
			};
		}

		public static dataQR.Ride ToModelData(this objQR.Ride source)
		{
			return new dataQR.Ride()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				DriverId = source.DriverId,
				DurationInSeconds = source.DurationInSeconds,
				End = source.End,
				EndLatitude = source.EndLatitude,
				EndLongitude = source.EndLongitude,
				GeoDistance = source.GeoDistance,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RideId = source.RideId,
				Start = source.Start,
				StartLatitude = source.StartLatitude,
				StartLongitude = source.StartLongitude,
				UserId = source.UserId,
				VehicleId = source.VehicleId,
			};
		}

		public static dataQR.RidePosition ToModelData(this objQR.RidePosition source)
		{
			return new dataQR.RidePosition()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				Latitude = source.Latitude,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RideId = source.RideId,
				RidePositionId = source.RidePositionId,
				Ts = source.Ts,
			};
		}

		public static dataQR.RideServiceType ToModelData(this objQR.RideServiceType source)
		{
			return new dataQR.RideServiceType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RideServiceTypeId = source.RideServiceTypeId,
			};
		}

		public static dataQR.User ToModelData(this objQR.User source)
		{
			return new dataQR.User()
			{
				BirthDate = source.BirthDate,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Email = source.Email,
				FirstName = source.FirstName,
				GenderTypeId = source.GenderTypeId,
				IsDeleted = source.IsDeleted,
				LastLogin = source.LastLogin,
				LastName = source.LastName,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				Password = source.Password,
				Salt = source.Salt,
				UserId = source.UserId,
				UserName = source.UserName,
			};
		}

		public static dataQR.UsersLocation ToModelData(this objQR.UsersLocation source)
		{
			return new dataQR.UsersLocation()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				LocationId = source.LocationId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				UserId = source.UserId,
			};
		}

		public static dataQR.UsersNotificationType ToModelData(this objQR.UsersNotificationType source)
		{
			return new dataQR.UsersNotificationType()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				NotificationTypeId = source.NotificationTypeId,
				UserId = source.UserId,
			};
		}

		public static dataQR.Vehicle ToModelData(this objQR.Vehicle source)
		{
			return new dataQR.Vehicle()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				EndDateInService = source.EndDateInService,
				IsDeleted = source.IsDeleted,
				Latitude = source.Latitude,
				LicensePlateNumber = source.LicensePlateNumber,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				StartDateInService = source.StartDateInService,
				VehicleId = source.VehicleId,
				VehicleStatusTypeId = source.VehicleStatusTypeId,
				VehicleTypeId = source.VehicleTypeId,
				Vin = source.Vin,
			};
		}

		public static dataQR.VehicleFeatureType ToModelData(this objQR.VehicleFeatureType source)
		{
			return new dataQR.VehicleFeatureType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				VehicleFeatureTypeId = source.VehicleFeatureTypeId,
			};
		}

		public static dataQR.VehicleStatusType ToModelData(this objQR.VehicleStatusType source)
		{
			return new dataQR.VehicleStatusType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				VehicleStatusTypeId = source.VehicleStatusTypeId,
			};
		}

		public static dataQR.VehicleType ToModelData(this objQR.VehicleType source)
		{
			return new dataQR.VehicleType()
			{
				Capacity = source.Capacity,
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				FrontOverhangInFeet = source.FrontOverhangInFeet,
				GroundClearanceInFeet = source.GroundClearanceInFeet,
				HeightInFeet = source.HeightInFeet,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				LengthInFeetMax = source.LengthInFeetMax,
				LengthInFeetMin = source.LengthInFeetMin,
				LengthWithBumpers = source.LengthWithBumpers,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RearOverhangInFeet = source.RearOverhangInFeet,
				VehicleTypeId = source.VehicleTypeId,
				WheelbaseInFeet = source.WheelbaseInFeet,
				WidthInFeet = source.WidthInFeet,
				WidthWithMirrorsInFeet = source.WidthWithMirrorsInFeet,
			};
		}

		public static dataQR.VehicleTypeVehicleFeatureType ToModelData(this objQR.VehicleTypeVehicleFeatureType source)
		{
			return new dataQR.VehicleTypeVehicleFeatureType()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				VehicleFeatureTypeId = source.VehicleFeatureTypeId,
				VehicleTypeId = source.VehicleTypeId,
			};
		}

		public static dataQR.VehicleVehicleFeatureType ToModelData(this objQR.VehicleVehicleFeatureType source)
		{
			return new dataQR.VehicleVehicleFeatureType()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				VehicleFeatureTypeId = source.VehicleFeatureTypeId,
				VehicleId = source.VehicleId,
			};
		}


		#endregion ModelObj to ModelData

		#region ModelData to ModelObj

		public static objQR.Driver ToModelObj(this dataQR.Driver source)
		{
			return new objQR.Driver()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				CurrentVehicleId = source.CurrentVehicleId,
				DataVersion = source.DataVersion,
				DriverId = source.DriverId,
				IsDeleted = source.IsDeleted,
				Latitude = source.Latitude,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				UserId = source.UserId,
			};
		}

		public static objQR.Feedback ToModelObj(this dataQR.Feedback source)
		{
			return new objQR.Feedback()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				Dispositioned = source.Dispositioned,
				DriverId = source.DriverId,
				FeedbackId = source.FeedbackId,
				FeedbackTypeId = source.FeedbackTypeId,
				IsDeleted = source.IsDeleted,
				Latitude = source.Latitude,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				Title = source.Title,
				UserId = source.UserId,
				VehicleId = source.VehicleId,
			};
		}

		public static objQR.FeedbackType ToModelObj(this dataQR.FeedbackType source)
		{
			return new objQR.FeedbackType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				FeedbackTypeId = source.FeedbackTypeId,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static objQR.GenderType ToModelObj(this dataQR.GenderType source)
		{
			return new objQR.GenderType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				GenderTypeId = source.GenderTypeId,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static objQR.Holiday ToModelObj(this dataQR.Holiday source)
		{
			return new objQR.Holiday()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Date = source.Date,
				DisplayText = source.DisplayText,
				HolidayId = source.HolidayId,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static objQR.LanguageType ToModelObj(this dataQR.LanguageType source)
		{
			return new objQR.LanguageType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageCultureIdentifier = source.LanguageCultureIdentifier,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				NativeName = source.NativeName,
				ThreeLetterIsoLanguageName = source.ThreeLetterIsoLanguageName,
				TwoLetterIsoLanguageName = source.TwoLetterIsoLanguageName,
			};
		}

		public static objQR.Location ToModelObj(this dataQR.Location source)
		{
			return new objQR.Location()
			{
				AddressLine1 = source.AddressLine1,
				AddressLine2 = source.AddressLine2,
				City = source.City,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				Latitude = source.Latitude,
				LocationId = source.LocationId,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				Name = source.Name,
				PostalCode = source.PostalCode,
				State = source.State,
			};
		}

		public static objQR.NotificationType ToModelObj(this dataQR.NotificationType source)
		{
			return new objQR.NotificationType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				NotificationTypeId = source.NotificationTypeId,
			};
		}

		public static objQR.Reservation ToModelObj(this dataQR.Reservation source)
		{
			return new objQR.Reservation()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				DestinationLocationId = source.DestinationLocationId,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				NumberOfAdults = source.NumberOfAdults,
				NumberOfBabies = source.NumberOfBabies,
				NumberOfBikes = source.NumberOfBikes,
				NumberOfChildren = source.NumberOfChildren,
				NumberOfWheelchairs = source.NumberOfWheelchairs,
				PersonalCareAttendantIncluded = source.PersonalCareAttendantIncluded,
				PickUpLocationId = source.PickUpLocationId,
				ReservationCancellationReasonId = source.ReservationCancellationReasonId,
				ReservationId = source.ReservationId,
				ReservationRequestOptionId = source.ReservationRequestOptionId,
				ReservationStatusTypeId = source.ReservationStatusTypeId,
				UserId = source.UserId,
			};
		}

		public static objQR.ReservationCancellationReasonType ToModelObj(this dataQR.ReservationCancellationReasonType source)
		{
			return new objQR.ReservationCancellationReasonType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ReservationCancellationReasonTypeId = source.ReservationCancellationReasonTypeId,
			};
		}

		public static objQR.ReservationRequest ToModelObj(this dataQR.ReservationRequest source)
		{
			return new objQR.ReservationRequest()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				DestinationLocationId = source.DestinationLocationId,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				NumberOfAdults = source.NumberOfAdults,
				NumberOfBabies = source.NumberOfBabies,
				NumberOfBikes = source.NumberOfBikes,
				NumberOfChildren = source.NumberOfChildren,
				NumberOfWheelchairs = source.NumberOfWheelchairs,
				PassengerRequiresAssistance = source.PassengerRequiresAssistance,
				PersonalCareAttendantIncluded = source.PersonalCareAttendantIncluded,
				PickupLocationId = source.PickupLocationId,
				ReplacesReservationId = source.ReplacesReservationId,
				RequestedArrivalEnd = source.RequestedArrivalEnd,
				RequestedArrivalStart = source.RequestedArrivalStart,
				RequestedPickupEnd = source.RequestedPickupEnd,
				RequestedPickupStart = source.RequestedPickupStart,
				ReservationId = source.ReservationId,
				ReservationRequestCancellationReasonTypeId = source.ReservationRequestCancellationReasonTypeId,
				ReservationRequestId = source.ReservationRequestId,
				ReservationRequestStatusTypeId = source.ReservationRequestStatusTypeId,
				UserId = source.UserId,
			};
		}

		public static objQR.ReservationRequestCancellationReasonType ToModelObj(this dataQR.ReservationRequestCancellationReasonType source)
		{
			return new objQR.ReservationRequestCancellationReasonType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ReservationRequestCancellationReasonTypeId = source.ReservationRequestCancellationReasonTypeId,
			};
		}

		public static objQR.ReservationRequestOption ToModelObj(this dataQR.ReservationRequestOption source)
		{
			return new objQR.ReservationRequestOption()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				EstimatedArrivalEnd = source.EstimatedArrivalEnd,
				EstimatedArrivalStart = source.EstimatedArrivalStart,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ReservationRequestId = source.ReservationRequestId,
				ReservationRequestOptionId = source.ReservationRequestOptionId,
				Score = source.Score,
				SuggestedPickupEnd = source.SuggestedPickupEnd,
				SuggestedPickupStart = source.SuggestedPickupStart,
			};
		}

		public static objQR.ReservationRequestStatusType ToModelObj(this dataQR.ReservationRequestStatusType source)
		{
			return new objQR.ReservationRequestStatusType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ReservationRequestStatusTypeId = source.ReservationRequestStatusTypeId,
			};
		}

		public static objQR.ReservationStatusType ToModelObj(this dataQR.ReservationStatusType source)
		{
			return new objQR.ReservationStatusType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ReservationStatusTypeId = source.ReservationStatusTypeId,
			};
		}

		public static objQR.Ride ToModelObj(this dataQR.Ride source)
		{
			return new objQR.Ride()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				DriverId = source.DriverId,
				DurationInSeconds = source.DurationInSeconds,
				End = source.End,
				EndLatitude = source.EndLatitude,
				EndLongitude = source.EndLongitude,
				GeoDistance = source.GeoDistance,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RideId = source.RideId,
				Start = source.Start,
				StartLatitude = source.StartLatitude,
				StartLongitude = source.StartLongitude,
				UserId = source.UserId,
				VehicleId = source.VehicleId,
			};
		}

		public static objQR.RidePosition ToModelObj(this dataQR.RidePosition source)
		{
			return new objQR.RidePosition()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				Latitude = source.Latitude,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RideId = source.RideId,
				RidePositionId = source.RidePositionId,
				Ts = source.Ts,
			};
		}

		public static objQR.RideServiceType ToModelObj(this dataQR.RideServiceType source)
		{
			return new objQR.RideServiceType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RideServiceTypeId = source.RideServiceTypeId,
			};
		}

		public static objQR.User ToModelObj(this dataQR.User source)
		{
			return new objQR.User()
			{
				BirthDate = source.BirthDate,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Email = source.Email,
				FirstName = source.FirstName,
				GenderTypeId = source.GenderTypeId,
				IsDeleted = source.IsDeleted,
				LastLogin = source.LastLogin,
				LastName = source.LastName,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				Password = source.Password,
				Salt = source.Salt,
				UserId = source.UserId,
				UserName = source.UserName,
			};
		}

		public static objQR.UsersLocation ToModelObj(this dataQR.UsersLocation source)
		{
			return new objQR.UsersLocation()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				LocationId = source.LocationId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				UserId = source.UserId,
			};
		}

		public static objQR.UsersNotificationType ToModelObj(this dataQR.UsersNotificationType source)
		{
			return new objQR.UsersNotificationType()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				NotificationTypeId = source.NotificationTypeId,
				UserId = source.UserId,
			};
		}

		public static objQR.Vehicle ToModelObj(this dataQR.Vehicle source)
		{
			return new objQR.Vehicle()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				EndDateInService = source.EndDateInService,
				IsDeleted = source.IsDeleted,
				Latitude = source.Latitude,
				LicensePlateNumber = source.LicensePlateNumber,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				StartDateInService = source.StartDateInService,
				VehicleId = source.VehicleId,
				VehicleStatusTypeId = source.VehicleStatusTypeId,
				VehicleTypeId = source.VehicleTypeId,
				Vin = source.Vin,
			};
		}

		public static objQR.VehicleFeatureType ToModelObj(this dataQR.VehicleFeatureType source)
		{
			return new objQR.VehicleFeatureType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				VehicleFeatureTypeId = source.VehicleFeatureTypeId,
			};
		}

		public static objQR.VehicleStatusType ToModelObj(this dataQR.VehicleStatusType source)
		{
			return new objQR.VehicleStatusType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				VehicleStatusTypeId = source.VehicleStatusTypeId,
			};
		}

		public static objQR.VehicleType ToModelObj(this dataQR.VehicleType source)
		{
			return new objQR.VehicleType()
			{
				Capacity = source.Capacity,
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				FrontOverhangInFeet = source.FrontOverhangInFeet,
				GroundClearanceInFeet = source.GroundClearanceInFeet,
				HeightInFeet = source.HeightInFeet,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				LengthInFeetMax = source.LengthInFeetMax,
				LengthInFeetMin = source.LengthInFeetMin,
				LengthWithBumpers = source.LengthWithBumpers,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RearOverhangInFeet = source.RearOverhangInFeet,
				VehicleTypeId = source.VehicleTypeId,
				WheelbaseInFeet = source.WheelbaseInFeet,
				WidthInFeet = source.WidthInFeet,
				WidthWithMirrorsInFeet = source.WidthWithMirrorsInFeet,
			};
		}

		public static objQR.VehicleTypeVehicleFeatureType ToModelObj(this dataQR.VehicleTypeVehicleFeatureType source)
		{
			return new objQR.VehicleTypeVehicleFeatureType()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				VehicleFeatureTypeId = source.VehicleFeatureTypeId,
				VehicleTypeId = source.VehicleTypeId,
			};
		}

		public static objQR.VehicleVehicleFeatureType ToModelObj(this dataQR.VehicleVehicleFeatureType source)
		{
			return new objQR.VehicleVehicleFeatureType()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				VehicleFeatureTypeId = source.VehicleFeatureTypeId,
				VehicleId = source.VehicleId,
			};
		}


		#endregion ModelData to ModelObj

	}
}
