// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CGH.QuikRide.Repository.Entities.QR
{

    // LanguageType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class LanguageType
    {
        public int LanguageTypeId { get; set; } // LanguageTypeId (Primary key)
        public string Code { get; set; } // Code (length: 50)
        public string DisplayText { get; set; } // DisplayText (length: 128)
        public int DisplayPriority { get; set; } // DisplayPriority
        public string NativeName { get; set; } // NativeName (length: 100)
        public string ThreeLetterIsoLanguageName { get; set; } // ThreeLetterISOLanguageName (length: 3)
        public string TwoLetterIsoLanguageName { get; set; } // TwoLetterISOLanguageName (length: 2)
        public int? LanguageCultureIdentifier { get; set; } // LanguageCultureIdentifier
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child BarcodeTypeTranslations where [BarcodeTypeTranslation].[LanguageTypeId] point to this entity (FK_BarcodeTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<BarcodeTypeTranslation> BarcodeTypeTranslations { get; set; } // BarcodeTypeTranslation.FK_BarcodeTypeTranslation_LanguageType
        /// <summary>
        /// Child BusRouteTranslations where [BusRouteTranslation].[LanguageTypeId] point to this entity (FK_BusRouteTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<BusRouteTranslation> BusRouteTranslations { get; set; } // BusRouteTranslation.FK_BusRouteTranslation_LanguageType
        /// <summary>
        /// Child FeedbackInitiatorTypeTranslations where [FeedbackInitiatorTypeTranslation].[LanguageTypeId] point to this entity (FK_FeedbackInitiatorTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<FeedbackInitiatorTypeTranslation> FeedbackInitiatorTypeTranslations { get; set; } // FeedbackInitiatorTypeTranslation.FK_FeedbackInitiatorTypeTranslation_LanguageType
        /// <summary>
        /// Child FeedbackTypeTranslations where [FeedbackTypeTranslation].[LanguageTypeId] point to this entity (FK_FeedbackTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<FeedbackTypeTranslation> FeedbackTypeTranslations { get; set; } // FeedbackTypeTranslation.FK_FeedbackTypeTranslation_LanguageType
        /// <summary>
        /// Child GenderTypeTranslations where [GenderTypeTranslation].[LanguageTypeId] point to this entity (FK_GenderTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<GenderTypeTranslation> GenderTypeTranslations { get; set; } // GenderTypeTranslation.FK_GenderTypeTranslation_LanguageType
        /// <summary>
        /// Child HolidayTranslations where [HolidayTranslation].[LanguageTypeId] point to this entity (FK_HolidayTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<HolidayTranslation> HolidayTranslations { get; set; } // HolidayTranslation.FK_HolidayTranslation_LanguageType
        /// <summary>
        /// Child LocationTypeTranslations where [LocationTypeTranslation].[LanguageTypeId] point to this entity (FK_LocationTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<LocationTypeTranslation> LocationTypeTranslations { get; set; } // LocationTypeTranslation.FK_LocationTypeTranslation_LanguageType
        /// <summary>
        /// Child NotificationTypeTranslations where [NotificationTypeTranslation].[LanguageTypeId] point to this entity (FK_NotificationTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<NotificationTypeTranslation> NotificationTypeTranslations { get; set; } // NotificationTypeTranslation.FK_NotificationTypeTranslation_LanguageType
        /// <summary>
        /// Child ReservationCancellationReasonTypeTranslations where [ReservationCancellationReasonTypeTranslation].[LanguageTypeId] point to this entity (FK_ReservationCancellationReasonTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<ReservationCancellationReasonTypeTranslation> ReservationCancellationReasonTypeTranslations { get; set; } // ReservationCancellationReasonTypeTranslation.FK_ReservationCancellationReasonTypeTranslation_LanguageType
        /// <summary>
        /// Child ReservationRequestCancellationReasonTypeTranslations where [ReservationRequestCancellationReasonTypeTranslation].[LanguageTypeId] point to this entity (FK_ReservationRequestCancellationReasonTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<ReservationRequestCancellationReasonTypeTranslation> ReservationRequestCancellationReasonTypeTranslations { get; set; } // ReservationRequestCancellationReasonTypeTranslation.FK_ReservationRequestCancellationReasonTypeTranslation_LanguageType
        /// <summary>
        /// Child ReservationRequestStatusTypeTranslations where [ReservationRequestStatusTypeTranslation].[LanguageTypeId] point to this entity (FK_ReservationRequestStatusTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<ReservationRequestStatusTypeTranslation> ReservationRequestStatusTypeTranslations { get; set; } // ReservationRequestStatusTypeTranslation.FK_ReservationRequestStatusTypeTranslation_LanguageType
        /// <summary>
        /// Child ReservationStatusTypeTranslations where [ReservationStatusTypeTranslation].[LanguageTypeId] point to this entity (FK_ReservationStatusTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<ReservationStatusTypeTranslation> ReservationStatusTypeTranslations { get; set; } // ReservationStatusTypeTranslation.FK_ReservationStatusTypeTranslation_LanguageType
        /// <summary>
        /// Child RideServiceTypeTranslations where [RideServiceTypeTranslation].[LanguageTypeId] point to this entity (FK_RideServiceTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<RideServiceTypeTranslation> RideServiceTypeTranslations { get; set; } // RideServiceTypeTranslation.FK_RideServiceTypeTranslation_LanguageType
        /// <summary>
        /// Child Users where [Users].[PreferredLanguageId] point to this entity (FK_Users_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<User> Users { get; set; } // Users.FK_Users_LanguageType
        /// <summary>
        /// Child UserRewardAccountTransactionTypeTranslations where [UserRewardAccountTransactionTypeTranslation].[LanguageTypeId] point to this entity (FK_UserRewardAccountTransactionTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<UserRewardAccountTransactionTypeTranslation> UserRewardAccountTransactionTypeTranslations { get; set; } // UserRewardAccountTransactionTypeTranslation.FK_UserRewardAccountTransactionTypeTranslation_LanguageType
        /// <summary>
        /// Child VehicleFeatureTypeTranslations where [VehicleFeatureTypeTranslation].[LanguageTypeId] point to this entity (FK_VehicleFeatureTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<VehicleFeatureTypeTranslation> VehicleFeatureTypeTranslations { get; set; } // VehicleFeatureTypeTranslation.FK_VehicleFeatureTypeTranslation_LanguageType
        /// <summary>
        /// Child VehicleStatusTypeTranslations where [VehicleStatusTypeTranslation].[LanguageTypeId] point to this entity (FK_VehicleStatusTypeTranslation_LanguageType)
        /// </summary>
        public System.Collections.Generic.ICollection<VehicleStatusTypeTranslation> VehicleStatusTypeTranslations { get; set; } // VehicleStatusTypeTranslation.FK_VehicleStatusTypeTranslation_LanguageType

        public LanguageType()
        {
            DisplayPriority = 100;
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            BarcodeTypeTranslations = new System.Collections.Generic.List<BarcodeTypeTranslation>();
            BusRouteTranslations = new System.Collections.Generic.List<BusRouteTranslation>();
            FeedbackInitiatorTypeTranslations = new System.Collections.Generic.List<FeedbackInitiatorTypeTranslation>();
            FeedbackTypeTranslations = new System.Collections.Generic.List<FeedbackTypeTranslation>();
            GenderTypeTranslations = new System.Collections.Generic.List<GenderTypeTranslation>();
            HolidayTranslations = new System.Collections.Generic.List<HolidayTranslation>();
            LocationTypeTranslations = new System.Collections.Generic.List<LocationTypeTranslation>();
            NotificationTypeTranslations = new System.Collections.Generic.List<NotificationTypeTranslation>();
            ReservationCancellationReasonTypeTranslations = new System.Collections.Generic.List<ReservationCancellationReasonTypeTranslation>();
            ReservationRequestCancellationReasonTypeTranslations = new System.Collections.Generic.List<ReservationRequestCancellationReasonTypeTranslation>();
            ReservationRequestStatusTypeTranslations = new System.Collections.Generic.List<ReservationRequestStatusTypeTranslation>();
            ReservationStatusTypeTranslations = new System.Collections.Generic.List<ReservationStatusTypeTranslation>();
            RideServiceTypeTranslations = new System.Collections.Generic.List<RideServiceTypeTranslation>();
            UserRewardAccountTransactionTypeTranslations = new System.Collections.Generic.List<UserRewardAccountTransactionTypeTranslation>();
            Users = new System.Collections.Generic.List<User>();
            VehicleFeatureTypeTranslations = new System.Collections.Generic.List<VehicleFeatureTypeTranslation>();
            VehicleStatusTypeTranslations = new System.Collections.Generic.List<VehicleStatusTypeTranslation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
