// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CGH.QuikRide.Repository.Entities.QR
{

    // ReservationRequestCancellationReasonType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ReservationRequestCancellationReasonType
    {
        public int ReservationRequestCancellationReasonTypeId { get; set; } // ReservationRequestCancellationReasonTypeId (Primary key)
        public string Code { get; set; } // Code (length: 50)
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child ReservationRequests where [ReservationRequest].[ReservationRequestCancellationReasonTypeId] point to this entity (FK_ReservationRequest_ReservationRequestCancellationReasonType)
        /// </summary>
        public System.Collections.Generic.ICollection<ReservationRequest> ReservationRequests { get; set; } // ReservationRequest.FK_ReservationRequest_ReservationRequestCancellationReasonType
        /// <summary>
        /// Child ReservationRequestCancellationReasonTypeTranslations where [ReservationRequestCancellationReasonTypeTranslation].[ReservationRequestCancellationReasonTypeId] point to this entity (FK_ReservationRequestCancellationReasonTypeTranslation_ReservationRequestCancellationReasonType)
        /// </summary>
        public System.Collections.Generic.ICollection<ReservationRequestCancellationReasonTypeTranslation> ReservationRequestCancellationReasonTypeTranslations { get; set; } // ReservationRequestCancellationReasonTypeTranslation.FK_ReservationRequestCancellationReasonTypeTranslation_ReservationRequestCancellationReasonType

        public ReservationRequestCancellationReasonType()
        {
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            ReservationRequests = new System.Collections.Generic.List<ReservationRequest>();
            ReservationRequestCancellationReasonTypeTranslations = new System.Collections.Generic.List<ReservationRequestCancellationReasonTypeTranslation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
