// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CGH.QuikRide.Repository.Entities.QR
{

    // Users
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class User
    {
        public int UserId { get; set; } // UserId (Primary key)
        public string UserName { get; set; } // UserName (length: 255)
        public string Email { get; set; } // Email (length: 255)
        public System.DateTime? BirthDate { get; set; } // BirthDate
        public string FirstName { get; set; } // FirstName (length: 255)
        public string LastName { get; set; } // LastName (length: 255)
        public int GenderTypeId { get; set; } // GenderTypeId
        public string Password { get; set; } // Password (length: 255)
        public string Salt { get; set; } // Salt (length: 255)
        public System.DateTime LastLogin { get; set; } // LastLogin
        public int PreferredLanguageId { get; set; } // PreferredLanguageId
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child Drivers where [Driver].[UserId] point to this entity (FK_Driver_Users)
        /// </summary>
        public System.Collections.Generic.ICollection<Driver> Drivers { get; set; } // Driver.FK_Driver_Users
        /// <summary>
        /// Child Reservations where [Reservation].[UserId] point to this entity (FK_Reservation_Users)
        /// </summary>
        public System.Collections.Generic.ICollection<Reservation> Reservations { get; set; } // Reservation.FK_Reservation_Users
        /// <summary>
        /// Child ReservationRequests where [ReservationRequest].[UserId] point to this entity (FK_ReservationRequest_Users)
        /// </summary>
        public System.Collections.Generic.ICollection<ReservationRequest> ReservationRequests { get; set; } // ReservationRequest.FK_ReservationRequest_Users
        /// <summary>
        /// Child Rides where [Ride].[UserId] point to this entity (FK_Ride_Users)
        /// </summary>
        public System.Collections.Generic.ICollection<Ride> Rides { get; set; } // Ride.FK_Ride_Users
        /// <summary>
        /// Child UsersLocations where [Users_Location].[UserId] point to this entity (FK_Users_Location_Users)
        /// </summary>
        public System.Collections.Generic.ICollection<UsersLocation> UsersLocations { get; set; } // Users_Location.FK_Users_Location_Users
        /// <summary>
        /// Child UsersNotificationTypes where [Users_NotificationType].[UserId] point to this entity (FK_Users_NotificationType_Users)
        /// </summary>
        public System.Collections.Generic.ICollection<UsersNotificationType> UsersNotificationTypes { get; set; } // Users_NotificationType.FK_Users_NotificationType_Users

        // Foreign keys

        /// <summary>
        /// Parent GenderType pointed by [Users].([GenderTypeId]) (FK_Users_GenderType_GenderTypeId)
        /// </summary>
        public GenderType GenderType { get; set; } // FK_Users_GenderType_GenderTypeId

        /// <summary>
        /// Parent LanguageType pointed by [Users].([PreferredLanguageId]) (FK_Users_LanguageType)
        /// </summary>
        public LanguageType LanguageType { get; set; } // FK_Users_LanguageType

        public User()
        {
            PreferredLanguageId = 1;
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            Drivers = new System.Collections.Generic.List<Driver>();
            Reservations = new System.Collections.Generic.List<Reservation>();
            ReservationRequests = new System.Collections.Generic.List<ReservationRequest>();
            Rides = new System.Collections.Generic.List<Ride>();
            UsersLocations = new System.Collections.Generic.List<UsersLocation>();
            UsersNotificationTypes = new System.Collections.Generic.List<UsersNotificationType>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
