// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CGH.QuikRide.Repository.Entities.QR
{

    // UserRewardAccountTransactionType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class UserRewardAccountTransactionType
    {
        public int UserRewardAccountTransactionTypeId { get; set; } // UserRewardAccountTransactionTypeId (Primary key)
        public string Code { get; set; } // Code (length: 50)
        public string DebitOrCredit { get; set; } // DebitOrCredit (length: 1)
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child UserRewardAccountTransactions where [UserRewardAccountTransaction].[UserRewardAccountTransactionTypeId] point to this entity (FK_UserRewardAccountTransaction_UserRewardAccountTransactionType)
        /// </summary>
        public System.Collections.Generic.ICollection<UserRewardAccountTransaction> UserRewardAccountTransactions { get; set; } // UserRewardAccountTransaction.FK_UserRewardAccountTransaction_UserRewardAccountTransactionType
        /// <summary>
        /// Child UserRewardAccountTransactionTypeTranslations where [UserRewardAccountTransactionTypeTranslation].[UserRewardAccountTransactionTypeId] point to this entity (FK_UserRewardAccountTransactionTypeTranslation_UserRewardAccountTransactionType)
        /// </summary>
        public System.Collections.Generic.ICollection<UserRewardAccountTransactionTypeTranslation> UserRewardAccountTransactionTypeTranslations { get; set; } // UserRewardAccountTransactionTypeTranslation.FK_UserRewardAccountTransactionTypeTranslation_UserRewardAccountTransactionType

        public UserRewardAccountTransactionType()
        {
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            UserRewardAccountTransactions = new System.Collections.Generic.List<UserRewardAccountTransaction>();
            UserRewardAccountTransactionTypeTranslations = new System.Collections.Generic.List<UserRewardAccountTransactionTypeTranslation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
