// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CGH.QuikRide.Repository.Entities.QR
{

    // VehicleStatusTypeTranslation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class VehicleStatusTypeTranslation
    {
        public int VehicleStatusTypeTranslationId { get; set; } // VehicleStatusTypeTranslationId (Primary key)
        public int VehicleStatusTypeId { get; set; } // VehicleStatusTypeId
        public int LanguageTypeId { get; set; } // LanguageTypeId
        public string Value { get; set; } // Value (length: 4000)
        public int DisplayPriority { get; set; } // DisplayPriority
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent LanguageType pointed by [VehicleStatusTypeTranslation].([LanguageTypeId]) (FK_VehicleStatusTypeTranslation_LanguageType)
        /// </summary>
        public LanguageType LanguageType { get; set; } // FK_VehicleStatusTypeTranslation_LanguageType

        /// <summary>
        /// Parent VehicleStatusType pointed by [VehicleStatusTypeTranslation].([VehicleStatusTypeId]) (FK_VehicleStatusTypeTranslation_VehicleStatusType)
        /// </summary>
        public VehicleStatusType VehicleStatusType { get; set; } // FK_VehicleStatusTypeTranslation_VehicleStatusType

        public VehicleStatusTypeTranslation()
        {
            DisplayPriority = 100;
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
