// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CGH.QuikRide.Repository.Entities.QR
{

    // Vehicle_BusRoute
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class VehicleBusRoute
    {
        public int VehicleId { get; set; } // VehicleId (Primary key)
        public int BusRouteId { get; set; } // BusRouteId (Primary key)
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent BusRoute pointed by [Vehicle_BusRoute].([BusRouteId]) (FK_Vehicle_BusRoute_BusRoute)
        /// </summary>
        public BusRoute BusRoute { get; set; } // FK_Vehicle_BusRoute_BusRoute

        /// <summary>
        /// Parent Vehicle pointed by [Vehicle_BusRoute].([VehicleId]) (FK_Vehicle_BusRoute_Vehicle)
        /// </summary>
        public Vehicle Vehicle { get; set; } // FK_Vehicle_BusRoute_Vehicle

        public VehicleBusRoute()
        {
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
