// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using SQLite;

namespace CGH.QuikRide.Xam.ModelData.QR
{
	[Table("FeedbackTypeTranslation")]
	public partial class FeedbackTypeTranslation
	{
		public string CreatedBy { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public int DataVersion { get; set; }
		public int DisplayPriority { get; set; }
		public int FeedbackTypeId { get; set; }

		[PrimaryKey]
		public int FeedbackTypeTranslationId { get; set; }

		public bool IsDeleted { get; set; }
		public int LanguageTypeId { get; set; }
		public string ModifiedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
		public string Value { get; set; }
	}
}
