// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.DTO.QR
{
	public static class DemoReservationStatusTypeTranslation
	{
		public static int SampleReservationStatusTypeTranslationId0000 = 1463017011;
		public static int SampleReservationStatusTypeTranslationId0100 = 442276856;

		public static ReservationStatusTypeTranslation SampleReservationStatusTypeTranslation00
		{
			get
			{
				return new ReservationStatusTypeTranslation()
				{
					ReservationStatusTypeTranslationId = SampleReservationStatusTypeTranslationId0000,
					ReservationStatusTypeId = 0,
					LanguageTypeId = 0,
					Value = "SampleValue",
					DisplayPriority = 0,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static ReservationStatusTypeTranslation SampleReservationStatusTypeTranslation01
		{
			get
			{
				return new ReservationStatusTypeTranslation()
				{
					ReservationStatusTypeTranslationId = SampleReservationStatusTypeTranslationId0100,
					ReservationStatusTypeId = 0,
					LanguageTypeId = 0,
					Value = "SampleValue",
					DisplayPriority = 0,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
