// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.DTO.QR
{
	public static class DemoVehicleStatusTypeTranslation
	{
		public static int SampleVehicleStatusTypeTranslationId0000 = 1013495054;
		public static int SampleVehicleStatusTypeTranslationId0100 = 510604927;

		public static VehicleStatusTypeTranslation SampleVehicleStatusTypeTranslation00
		{
			get
			{
				return new VehicleStatusTypeTranslation()
				{
					VehicleStatusTypeTranslationId = SampleVehicleStatusTypeTranslationId0000,
					VehicleStatusTypeId = 0,
					LanguageTypeId = 0,
					Value = "SampleValue",
					DisplayPriority = 0,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static VehicleStatusTypeTranslation SampleVehicleStatusTypeTranslation01
		{
			get
			{
				return new VehicleStatusTypeTranslation()
				{
					VehicleStatusTypeTranslationId = SampleVehicleStatusTypeTranslationId0100,
					VehicleStatusTypeId = 0,
					LanguageTypeId = 0,
					Value = "SampleValue",
					DisplayPriority = 0,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
