// <auto-generated> - Template:ModelsBackedByDto, Version:1.1, Id:f1539c0d-024f-4b1f-b346-132cdd9dd31f
using CodeGenHero.Logging;
using CodeGenHero.DataService;
using System;
using System.Collections.Generic;
using System.Linq;
using CGH.QuikRide.API.Client.Interface;
using CGH.QuikRide.Model.QR.Interface;
using xDTO = CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.Model.QR
{

	public class LoadRequestBarcodeScanLog : EventArgs
	{
		public LoadRequestBarcodeScanLog(string propertyNameRequestingLoad)
		{
			PropertyNameRequestingLoad = propertyNameRequestingLoad;
		}

		public string PropertyNameRequestingLoad { get; set; }
	}


	public partial class BarcodeScanLog : BaseModel<IWebApiDataServiceQR>, IBarcodeScanLog
	{
		public event EventHandler<LoadRequestBarcodeScanLog> OnLazyLoadRequest = delegate { }; // Empty delegate. Thus we are sure that value is always != null because no one outside of the class can change it.
		private xDTO.BarcodeScanLog _dto = null;

		public BarcodeScanLog(ILoggingService log, IDataService<IWebApiDataServiceQR> dataService) : base(log, dataService)
		{
			_dto = new xDTO.BarcodeScanLog();
			OnLazyLoadRequest += HandleLazyLoadRequest;
		}

		public BarcodeScanLog(ILoggingService log, IDataService<IWebApiDataServiceQR> dataService, xDTO.BarcodeScanLog dto) : this(log, dataService)
		{
			_dto = dto;
		}


		public virtual System.Guid BarcodeId { get { return _dto.BarcodeId; } }
		public virtual System.Guid BarcodeScanLogId { get { return _dto.BarcodeScanLogId; } }
		public virtual string CreatedBy { get { return _dto.CreatedBy; } }
		public virtual System.DateTime CreatedUtcDate { get { return _dto.CreatedUtcDate; } }
		public virtual string DataJson { get { return _dto.DataJson; } }
		public virtual int DataVersion { get { return _dto.DataVersion; } }
		public virtual string DeviceOperatingSystem { get { return _dto.DeviceOperatingSystem; } }
		public virtual string DeviceOperatingSystemVersion { get { return _dto.DeviceOperatingSystemVersion; } }
		public virtual bool IsDeleted { get { return _dto.IsDeleted; } }
		public virtual double? Latitude { get { return _dto.Latitude; } }
		public virtual double? Longitude { get { return _dto.Longitude; } }
		public virtual string ModifiedBy { get { return _dto.ModifiedBy; } }
		public virtual System.DateTime ModifiedUtcDate { get { return _dto.ModifiedUtcDate; } }
		public virtual int UserId { get { return _dto.UserId; } }

		private IBarcode _barcode = null; // Foreign Key


		public virtual IBarcode Barcode
		{
			get
			{
				if (_barcode == null && _dto != null && _dto.Barcode != null)
				{
					_barcode = new Barcode(Log, DataService, _dto.Barcode);
				}

				return _barcode;
			}
		}



	}
}
