// <auto-generated> - Template:ModelsBackedByDto, Version:1.1, Id:f1539c0d-024f-4b1f-b346-132cdd9dd31f
using CodeGenHero.Logging;
using CodeGenHero.DataService;
using System;
using System.Collections.Generic;
using System.Linq;
using CGH.QuikRide.API.Client.Interface;
using CGH.QuikRide.Model.QR.Interface;
using xDTO = CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.Model.QR
{

	public class LoadRequestNotificationTypeTranslation : EventArgs
	{
		public LoadRequestNotificationTypeTranslation(string propertyNameRequestingLoad)
		{
			PropertyNameRequestingLoad = propertyNameRequestingLoad;
		}

		public string PropertyNameRequestingLoad { get; set; }
	}


	public partial class NotificationTypeTranslation : BaseModel<IWebApiDataServiceQR>, INotificationTypeTranslation
	{
		public event EventHandler<LoadRequestNotificationTypeTranslation> OnLazyLoadRequest = delegate { }; // Empty delegate. Thus we are sure that value is always != null because no one outside of the class can change it.
		private xDTO.NotificationTypeTranslation _dto = null;

		public NotificationTypeTranslation(ILoggingService log, IDataService<IWebApiDataServiceQR> dataService) : base(log, dataService)
		{
			_dto = new xDTO.NotificationTypeTranslation();
			OnLazyLoadRequest += HandleLazyLoadRequest;
		}

		public NotificationTypeTranslation(ILoggingService log, IDataService<IWebApiDataServiceQR> dataService, xDTO.NotificationTypeTranslation dto) : this(log, dataService)
		{
			_dto = dto;
		}


		public virtual string CreatedBy { get { return _dto.CreatedBy; } }
		public virtual System.DateTime CreatedUtcDate { get { return _dto.CreatedUtcDate; } }
		public virtual int DataVersion { get { return _dto.DataVersion; } }
		public virtual int DisplayPriority { get { return _dto.DisplayPriority; } }
		public virtual bool IsDeleted { get { return _dto.IsDeleted; } }
		public virtual int LanguageTypeId { get { return _dto.LanguageTypeId; } }
		public virtual string ModifiedBy { get { return _dto.ModifiedBy; } }
		public virtual System.DateTime ModifiedUtcDate { get { return _dto.ModifiedUtcDate; } }
		public virtual int NotificationTypeId { get { return _dto.NotificationTypeId; } }
		public virtual int NotificationTypeTranslationId { get { return _dto.NotificationTypeTranslationId; } }
		public virtual string Value { get { return _dto.Value; } }

		private ILanguageType _languageType = null; // Foreign Key
		private INotificationType _notificationType = null; // Foreign Key


		public virtual ILanguageType LanguageType
		{
			get
			{
				if (_languageType == null && _dto != null && _dto.LanguageType != null)
				{
					_languageType = new LanguageType(Log, DataService, _dto.LanguageType);
				}

				return _languageType;
			}
		}

		public virtual INotificationType NotificationType
		{
			get
			{
				if (_notificationType == null)
				{
					OnLazyLoadRequest(this, new LoadRequestNotificationTypeTranslation(nameof(NotificationType)));
				}

				return _notificationType;
			}
		}



	}
}
