// <auto-generated> - Template:ModelsBackedByDto, Version:1.1, Id:f1539c0d-024f-4b1f-b346-132cdd9dd31f
using CodeGenHero.Logging;
using CodeGenHero.DataService;
using System;
using System.Collections.Generic;
using System.Linq;
using CGH.QuikRide.API.Client.Interface;
using CGH.QuikRide.Model.QR.Interface;
using xDTO = CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.Model.QR
{

	public class LoadRequestReservationRequestStatusType : EventArgs
	{
		public LoadRequestReservationRequestStatusType(string propertyNameRequestingLoad)
		{
			PropertyNameRequestingLoad = propertyNameRequestingLoad;
		}

		public string PropertyNameRequestingLoad { get; set; }
	}


	public partial class ReservationRequestStatusType : BaseModel<IWebApiDataServiceQR>, IReservationRequestStatusType
	{
		public event EventHandler<LoadRequestReservationRequestStatusType> OnLazyLoadRequest = delegate { }; // Empty delegate. Thus we are sure that value is always != null because no one outside of the class can change it.
		private xDTO.ReservationRequestStatusType _dto = null;

		public ReservationRequestStatusType(ILoggingService log, IDataService<IWebApiDataServiceQR> dataService) : base(log, dataService)
		{
			_dto = new xDTO.ReservationRequestStatusType();
			OnLazyLoadRequest += HandleLazyLoadRequest;
		}

		public ReservationRequestStatusType(ILoggingService log, IDataService<IWebApiDataServiceQR> dataService, xDTO.ReservationRequestStatusType dto) : this(log, dataService)
		{
			_dto = dto;
		}


		public virtual string Code { get { return _dto.Code; } }
		public virtual string CreatedBy { get { return _dto.CreatedBy; } }
		public virtual System.DateTime CreatedUtcDate { get { return _dto.CreatedUtcDate; } }
		public virtual int DataVersion { get { return _dto.DataVersion; } }
		public virtual bool IsDeleted { get { return _dto.IsDeleted; } }
		public virtual string ModifiedBy { get { return _dto.ModifiedBy; } }
		public virtual System.DateTime ModifiedUtcDate { get { return _dto.ModifiedUtcDate; } }
		public virtual int ReservationRequestStatusTypeId { get { return _dto.ReservationRequestStatusTypeId; } }

		private List<IReservationRequest> _reservationRequests = null; // Reverse Navigation
		private List<IReservationRequestStatusTypeTranslation> _reservationRequestStatusTypeTranslations = null; // Reverse Navigation


		public virtual List<IReservationRequest> ReservationRequests
		{
			get
			{
				if (_reservationRequests == null)
				{
					OnLazyLoadRequest(this, new LoadRequestReservationRequestStatusType(nameof(ReservationRequests)));
				}

				return _reservationRequests;
			}
		}

		public virtual List<IReservationRequestStatusTypeTranslation> ReservationRequestStatusTypeTranslations
		{
			get
			{
				if (_reservationRequestStatusTypeTranslations == null && _dto != null)
				{	// The core DTO object is loaded, but this property is not loaded.
					if (_dto.ReservationRequestStatusTypeTranslations != null)
					{	// The core DTO object has data for this property, load it into the model.
						_reservationRequestStatusTypeTranslations = new List<IReservationRequestStatusTypeTranslation>();
						foreach (var dtoItem in _dto.ReservationRequestStatusTypeTranslations)
						{
							_reservationRequestStatusTypeTranslations.Add(new ReservationRequestStatusTypeTranslation(Log, DataService, dtoItem));
						}
					}
					else
					{	// Trigger the load data request - The core DTO object is loaded and does not have data for this property.
						OnLazyLoadRequest(this, new LoadRequestReservationRequestStatusType(nameof(ReservationRequestStatusTypeTranslations)));
					}
				}

				return _reservationRequestStatusTypeTranslations;
			}
		}



	}
}
