// <auto-generated> - Template:ModelsBackedByDto, Version:1.1, Id:f1539c0d-024f-4b1f-b346-132cdd9dd31f
using CodeGenHero.Logging;
using CodeGenHero.DataService;
using System;
using System.Collections.Generic;
using System.Linq;
using CGH.QuikRide.API.Client.Interface;
using CGH.QuikRide.Model.QR.Interface;
using xDTO = CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.Model.QR
{

	public class LoadRequestVehicleFeatureTypeTranslation : EventArgs
	{
		public LoadRequestVehicleFeatureTypeTranslation(string propertyNameRequestingLoad)
		{
			PropertyNameRequestingLoad = propertyNameRequestingLoad;
		}

		public string PropertyNameRequestingLoad { get; set; }
	}


	public partial class VehicleFeatureTypeTranslation : BaseModel<IWebApiDataServiceQR>, IVehicleFeatureTypeTranslation
	{
		public event EventHandler<LoadRequestVehicleFeatureTypeTranslation> OnLazyLoadRequest = delegate { }; // Empty delegate. Thus we are sure that value is always != null because no one outside of the class can change it.
		private xDTO.VehicleFeatureTypeTranslation _dto = null;

		public VehicleFeatureTypeTranslation(ILoggingService log, IDataService<IWebApiDataServiceQR> dataService) : base(log, dataService)
		{
			_dto = new xDTO.VehicleFeatureTypeTranslation();
			OnLazyLoadRequest += HandleLazyLoadRequest;
		}

		public VehicleFeatureTypeTranslation(ILoggingService log, IDataService<IWebApiDataServiceQR> dataService, xDTO.VehicleFeatureTypeTranslation dto) : this(log, dataService)
		{
			_dto = dto;
		}


		public virtual string CreatedBy { get { return _dto.CreatedBy; } }
		public virtual System.DateTime CreatedUtcDate { get { return _dto.CreatedUtcDate; } }
		public virtual int DataVersion { get { return _dto.DataVersion; } }
		public virtual int DisplayPriority { get { return _dto.DisplayPriority; } }
		public virtual bool IsDeleted { get { return _dto.IsDeleted; } }
		public virtual int LanguageTypeId { get { return _dto.LanguageTypeId; } }
		public virtual string ModifiedBy { get { return _dto.ModifiedBy; } }
		public virtual System.DateTime ModifiedUtcDate { get { return _dto.ModifiedUtcDate; } }
		public virtual string Value { get { return _dto.Value; } }
		public virtual int VehicleFeatureTypeId { get { return _dto.VehicleFeatureTypeId; } }
		public virtual int VehicleFeatureTypeTranslationId { get { return _dto.VehicleFeatureTypeTranslationId; } }

		private ILanguageType _languageType = null; // Foreign Key
		private IVehicleFeatureType _vehicleFeatureType = null; // Foreign Key


		public virtual ILanguageType LanguageType
		{
			get
			{
				if (_languageType == null && _dto != null && _dto.LanguageType != null)
				{
					_languageType = new LanguageType(Log, DataService, _dto.LanguageType);
				}

				return _languageType;
			}
		}

		public virtual IVehicleFeatureType VehicleFeatureType
		{
			get
			{
				if (_vehicleFeatureType == null)
				{
					OnLazyLoadRequest(this, new LoadRequestVehicleFeatureTypeTranslation(nameof(VehicleFeatureType)));
				}

				return _vehicleFeatureType;
			}
		}



	}
}
