// <auto-generated> - Template:ModelsBackedByDto, Version:1.1, Id:f1539c0d-024f-4b1f-b346-132cdd9dd31f
using CodeGenHero.Logging;
using CodeGenHero.DataService;
using System;
using System.Collections.Generic;
using System.Linq;
using CGH.QuikRide.API.Client.Interface;
using CGH.QuikRide.Model.QR.Interface;
using xDTO = CGH.QuikRide.DTO.QR;

namespace CGH.QuikRide.Model.QR
{

	public class LoadRequestVehicleFeatureType : EventArgs
	{
		public LoadRequestVehicleFeatureType(string propertyNameRequestingLoad)
		{
			PropertyNameRequestingLoad = propertyNameRequestingLoad;
		}

		public string PropertyNameRequestingLoad { get; set; }
	}


	public partial class VehicleFeatureType : BaseModel<IWebApiDataServiceQR>, IVehicleFeatureType
	{
		public event EventHandler<LoadRequestVehicleFeatureType> OnLazyLoadRequest = delegate { }; // Empty delegate. Thus we are sure that value is always != null because no one outside of the class can change it.
		private xDTO.VehicleFeatureType _dto = null;

		public VehicleFeatureType(ILoggingService log, IDataService<IWebApiDataServiceQR> dataService) : base(log, dataService)
		{
			_dto = new xDTO.VehicleFeatureType();
			OnLazyLoadRequest += HandleLazyLoadRequest;
		}

		public VehicleFeatureType(ILoggingService log, IDataService<IWebApiDataServiceQR> dataService, xDTO.VehicleFeatureType dto) : this(log, dataService)
		{
			_dto = dto;
		}


		public virtual string Code { get { return _dto.Code; } }
		public virtual string CreatedBy { get { return _dto.CreatedBy; } }
		public virtual System.DateTime CreatedUtcDate { get { return _dto.CreatedUtcDate; } }
		public virtual int DataVersion { get { return _dto.DataVersion; } }
		public virtual bool IsDeleted { get { return _dto.IsDeleted; } }
		public virtual string ModifiedBy { get { return _dto.ModifiedBy; } }
		public virtual System.DateTime ModifiedUtcDate { get { return _dto.ModifiedUtcDate; } }
		public virtual int VehicleFeatureTypeId { get { return _dto.VehicleFeatureTypeId; } }

		private List<IVehicleFeatureTypeTranslation> _vehicleFeatureTypeTranslations = null; // Reverse Navigation
		private List<IVehicleTypeVehicleFeatureType> _vehicleTypeVehicleFeatureTypes = null; // Reverse Navigation
		private List<IVehicleVehicleFeatureType> _vehicleVehicleFeatureTypes = null; // Reverse Navigation


		public virtual List<IVehicleFeatureTypeTranslation> VehicleFeatureTypeTranslations
		{
			get
			{
				if (_vehicleFeatureTypeTranslations == null && _dto != null)
				{	// The core DTO object is loaded, but this property is not loaded.
					if (_dto.VehicleFeatureTypeTranslations != null)
					{	// The core DTO object has data for this property, load it into the model.
						_vehicleFeatureTypeTranslations = new List<IVehicleFeatureTypeTranslation>();
						foreach (var dtoItem in _dto.VehicleFeatureTypeTranslations)
						{
							_vehicleFeatureTypeTranslations.Add(new VehicleFeatureTypeTranslation(Log, DataService, dtoItem));
						}
					}
					else
					{	// Trigger the load data request - The core DTO object is loaded and does not have data for this property.
						OnLazyLoadRequest(this, new LoadRequestVehicleFeatureType(nameof(VehicleFeatureTypeTranslations)));
					}
				}

				return _vehicleFeatureTypeTranslations;
			}
		}

		public virtual List<IVehicleTypeVehicleFeatureType> VehicleTypeVehicleFeatureTypes
		{
			get
			{
				if (_vehicleTypeVehicleFeatureTypes == null && _dto != null)
				{	// The core DTO object is loaded, but this property is not loaded.
					if (_dto.VehicleTypeVehicleFeatureTypes != null)
					{	// The core DTO object has data for this property, load it into the model.
						_vehicleTypeVehicleFeatureTypes = new List<IVehicleTypeVehicleFeatureType>();
						foreach (var dtoItem in _dto.VehicleTypeVehicleFeatureTypes)
						{
							_vehicleTypeVehicleFeatureTypes.Add(new VehicleTypeVehicleFeatureType(Log, DataService, dtoItem));
						}
					}
					else
					{	// Trigger the load data request - The core DTO object is loaded and does not have data for this property.
						OnLazyLoadRequest(this, new LoadRequestVehicleFeatureType(nameof(VehicleTypeVehicleFeatureTypes)));
					}
				}

				return _vehicleTypeVehicleFeatureTypes;
			}
		}

		public virtual List<IVehicleVehicleFeatureType> VehicleVehicleFeatureTypes
		{
			get
			{
				if (_vehicleVehicleFeatureTypes == null)
				{
					OnLazyLoadRequest(this, new LoadRequestVehicleFeatureType(nameof(VehicleVehicleFeatureTypes)));
				}

				return _vehicleVehicleFeatureTypes;
			}
		}



	}
}
