// <auto-generated> - Template:MvvmLightModelObject, Version:1.1, Id:c644a31c-7ebc-4383-bc7f-0ea7c5bf6ed4
using GalaSoft.MvvmLight;

namespace CGH.QuikRide.Xam.ModelObj.QR
{
	public partial class BarcodeScanLog : ObservableObject
	{
		public BarcodeScanLog()
		{
			InitializePartial();
		}

		private System.Guid _barcodeId;
		private System.Guid _barcodeScanLogId;
		private string _createdBy;
		private System.DateTime _createdUtcDate;
		private string _dataJson;
		private int _dataVersion;
		private string _deviceOperatingSystem;
		private string _deviceOperatingSystemVersion;
		private bool _isDeleted;
		private double? _latitude;
		private double? _longitude;
		private string _modifiedBy;
		private System.DateTime _modifiedUtcDate;
		private int _userId;


		public System.Guid BarcodeId
		{
			get { return _barcodeId; }
			set
			{
				Set<System.Guid>(() => BarcodeId, ref _barcodeId, value);
				RunCustomLogicSetBarcodeId(value);
			}
		}

		public System.Guid BarcodeScanLogId
		{
			get { return _barcodeScanLogId; }
			set
			{
				Set<System.Guid>(() => BarcodeScanLogId, ref _barcodeScanLogId, value);
				RunCustomLogicSetBarcodeScanLogId(value);
			}
		}

		public string CreatedBy
		{
			get { return _createdBy; }
			set
			{
				Set<string>(() => CreatedBy, ref _createdBy, value);
				RunCustomLogicSetCreatedBy(value);
			}
		}

		public System.DateTime CreatedUtcDate
		{
			get { return _createdUtcDate; }
			set
			{
				Set<System.DateTime>(() => CreatedUtcDate, ref _createdUtcDate, value);
				RunCustomLogicSetCreatedUtcDate(value);
			}
		}

		public string DataJson
		{
			get { return _dataJson; }
			set
			{
				Set<string>(() => DataJson, ref _dataJson, value);
				RunCustomLogicSetDataJson(value);
			}
		}

		public int DataVersion
		{
			get { return _dataVersion; }
			set
			{
				Set<int>(() => DataVersion, ref _dataVersion, value);
				RunCustomLogicSetDataVersion(value);
			}
		}

		public string DeviceOperatingSystem
		{
			get { return _deviceOperatingSystem; }
			set
			{
				Set<string>(() => DeviceOperatingSystem, ref _deviceOperatingSystem, value);
				RunCustomLogicSetDeviceOperatingSystem(value);
			}
		}

		public string DeviceOperatingSystemVersion
		{
			get { return _deviceOperatingSystemVersion; }
			set
			{
				Set<string>(() => DeviceOperatingSystemVersion, ref _deviceOperatingSystemVersion, value);
				RunCustomLogicSetDeviceOperatingSystemVersion(value);
			}
		}

		public bool IsDeleted
		{
			get { return _isDeleted; }
			set
			{
				Set<bool>(() => IsDeleted, ref _isDeleted, value);
				RunCustomLogicSetIsDeleted(value);
			}
		}

		public double? Latitude
		{
			get { return _latitude; }
			set
			{
				Set<double?>(() => Latitude, ref _latitude, value);
				RunCustomLogicSetLatitude(value);
			}
		}

		public double? Longitude
		{
			get { return _longitude; }
			set
			{
				Set<double?>(() => Longitude, ref _longitude, value);
				RunCustomLogicSetLongitude(value);
			}
		}

		public string ModifiedBy
		{
			get { return _modifiedBy; }
			set
			{
				Set<string>(() => ModifiedBy, ref _modifiedBy, value);
				RunCustomLogicSetModifiedBy(value);
			}
		}

		public System.DateTime ModifiedUtcDate
		{
			get { return _modifiedUtcDate; }
			set
			{
				Set<System.DateTime>(() => ModifiedUtcDate, ref _modifiedUtcDate, value);
				RunCustomLogicSetModifiedUtcDate(value);
			}
		}

		public int UserId
		{
			get { return _userId; }
			set
			{
				Set<int>(() => UserId, ref _userId, value);
				RunCustomLogicSetUserId(value);
			}
		}

		public virtual Barcode Barcode { get; set; } 


		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetBarcodeId(System.Guid value);
		partial void RunCustomLogicSetBarcodeScanLogId(System.Guid value);
		partial void RunCustomLogicSetCreatedBy(string value);
		partial void RunCustomLogicSetCreatedUtcDate(System.DateTime value);
		partial void RunCustomLogicSetDataJson(string value);
		partial void RunCustomLogicSetDataVersion(int value);
		partial void RunCustomLogicSetDeviceOperatingSystem(string value);
		partial void RunCustomLogicSetDeviceOperatingSystemVersion(string value);
		partial void RunCustomLogicSetIsDeleted(bool value);
		partial void RunCustomLogicSetLatitude(double? value);
		partial void RunCustomLogicSetLongitude(double? value);
		partial void RunCustomLogicSetModifiedBy(string value);
		partial void RunCustomLogicSetModifiedUtcDate(System.DateTime value);
		partial void RunCustomLogicSetUserId(int value);

		#endregion RunCustomLogicSet

	}
}
