// <auto-generated> - Template:MvvmLightModelObject, Version:1.1, Id:c644a31c-7ebc-4383-bc7f-0ea7c5bf6ed4
using GalaSoft.MvvmLight;

namespace CGH.QuikRide.Xam.ModelObj.QR
{
	public partial class DriverShift : ObservableObject
	{
		public DriverShift()
		{
			InitializePartial();
		}

		private string _createdBy;
		private System.DateTime _createdUtcDate;
		private int _dataVersion;
		private int _driverId;
		private System.Guid _driverShiftId;
		private System.DateTime _endUtcDate;
		private bool _isDeleted;
		private string _modifiedBy;
		private System.DateTime _modifiedUtcDate;
		private System.DateTime _startUtcDate;


		public string CreatedBy
		{
			get { return _createdBy; }
			set
			{
				Set<string>(() => CreatedBy, ref _createdBy, value);
				RunCustomLogicSetCreatedBy(value);
			}
		}

		public System.DateTime CreatedUtcDate
		{
			get { return _createdUtcDate; }
			set
			{
				Set<System.DateTime>(() => CreatedUtcDate, ref _createdUtcDate, value);
				RunCustomLogicSetCreatedUtcDate(value);
			}
		}

		public int DataVersion
		{
			get { return _dataVersion; }
			set
			{
				Set<int>(() => DataVersion, ref _dataVersion, value);
				RunCustomLogicSetDataVersion(value);
			}
		}

		public int DriverId
		{
			get { return _driverId; }
			set
			{
				Set<int>(() => DriverId, ref _driverId, value);
				RunCustomLogicSetDriverId(value);
			}
		}

		public System.Guid DriverShiftId
		{
			get { return _driverShiftId; }
			set
			{
				Set<System.Guid>(() => DriverShiftId, ref _driverShiftId, value);
				RunCustomLogicSetDriverShiftId(value);
			}
		}

		public System.DateTime EndUtcDate
		{
			get { return _endUtcDate; }
			set
			{
				Set<System.DateTime>(() => EndUtcDate, ref _endUtcDate, value);
				RunCustomLogicSetEndUtcDate(value);
			}
		}

		public bool IsDeleted
		{
			get { return _isDeleted; }
			set
			{
				Set<bool>(() => IsDeleted, ref _isDeleted, value);
				RunCustomLogicSetIsDeleted(value);
			}
		}

		public string ModifiedBy
		{
			get { return _modifiedBy; }
			set
			{
				Set<string>(() => ModifiedBy, ref _modifiedBy, value);
				RunCustomLogicSetModifiedBy(value);
			}
		}

		public System.DateTime ModifiedUtcDate
		{
			get { return _modifiedUtcDate; }
			set
			{
				Set<System.DateTime>(() => ModifiedUtcDate, ref _modifiedUtcDate, value);
				RunCustomLogicSetModifiedUtcDate(value);
			}
		}

		public System.DateTime StartUtcDate
		{
			get { return _startUtcDate; }
			set
			{
				Set<System.DateTime>(() => StartUtcDate, ref _startUtcDate, value);
				RunCustomLogicSetStartUtcDate(value);
			}
		}



		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetCreatedBy(string value);
		partial void RunCustomLogicSetCreatedUtcDate(System.DateTime value);
		partial void RunCustomLogicSetDataVersion(int value);
		partial void RunCustomLogicSetDriverId(int value);
		partial void RunCustomLogicSetDriverShiftId(System.Guid value);
		partial void RunCustomLogicSetEndUtcDate(System.DateTime value);
		partial void RunCustomLogicSetIsDeleted(bool value);
		partial void RunCustomLogicSetModifiedBy(string value);
		partial void RunCustomLogicSetModifiedUtcDate(System.DateTime value);
		partial void RunCustomLogicSetStartUtcDate(System.DateTime value);

		#endregion RunCustomLogicSet

	}
}
