// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace CGH.QuikRide.Model.QR.Interface
{
	public partial interface IFeedback
	{
		string CreatedBy { get; }
		System.DateTime CreatedUtcDate { get; }
		int DataVersion { get; }
		string Description { get; }
		bool Dispositioned { get; }
		int? DriverId { get; }
		System.Guid FeedbackId { get; }
		int FeedbackTypeId { get; }
		bool IsDeleted { get; }
		double Latitude { get; }
		double Longitude { get; }
		string ModifiedBy { get; }
		System.DateTime ModifiedUtcDate { get; }
		string Title { get; }
		int UserId { get; }
		int? VehicleId { get; }

		IFeedbackType FeedbackType { get; }


	}
}
