// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace CGH.QuikRide.Model.QR.Interface
{
	public partial interface ILanguageType
	{
		string Code { get; }
		string CreatedBy { get; }
		System.DateTime CreatedUtcDate { get; }
		int DataVersion { get; }
		int DisplayPriority { get; }
		string DisplayText { get; }
		bool IsDeleted { get; }
		int? LanguageCultureIdentifier { get; }
		int LanguageTypeId { get; }
		string ModifiedBy { get; }
		System.DateTime ModifiedUtcDate { get; }
		string NativeName { get; }
		string ThreeLetterIsoLanguageName { get; }
		string TwoLetterIsoLanguageName { get; }

		List<IFeedbackType> FeedbackTypes { get; }
		List<IGenderType> GenderTypes { get; }
		List<INotificationType> NotificationTypes { get; }
		List<IReservationCancellationReasonType> ReservationCancellationReasonTypes { get; }
		List<IReservationRequestCancellationReasonType> ReservationRequestCancellationReasonTypes { get; }
		List<IReservationRequestStatusType> ReservationRequestStatusTypes { get; }
		List<IReservationStatusType> ReservationStatusTypes { get; }
		List<IRideServiceType> RideServiceTypes { get; }
		List<IVehicleFeatureType> VehicleFeatureTypes { get; }
		List<IVehicleStatusType> VehicleStatusTypes { get; }
		List<IVehicleType> VehicleTypes { get; }


	}
}
