// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace CGH.QuikRide.Model.QR.Interface
{
	public partial interface ILocation
	{
		string AddressLine1 { get; }
		string AddressLine2 { get; }
		string City { get; }
		string CreatedBy { get; }
		System.DateTime CreatedUtcDate { get; }
		int DataVersion { get; }
		bool IsDeleted { get; }
		double? Latitude { get; }
		System.Guid LocationId { get; }
		double? Longitude { get; }
		string ModifiedBy { get; }
		System.DateTime ModifiedUtcDate { get; }
		string Name { get; }
		string PostalCode { get; }
		string State { get; }

		List<IReservation> Reservations { get; }
		List<IReservationRequest> DestinationLocation { get; }
		List<IReservationRequest> PickupLocation { get; }
		List<IUsersLocation> UsersLocations { get; }


	}
}
