// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace CGH.QuikRide.Model.QR.Interface
{
	public partial interface IReservationRequestOption
	{
		string CreatedBy { get; }
		System.DateTime CreatedUtcDate { get; }
		int DataVersion { get; }
		System.DateTime EstimatedArrivalEnd { get; }
		System.DateTime EstimatedArrivalStart { get; }
		bool IsDeleted { get; }
		string ModifiedBy { get; }
		System.DateTime ModifiedUtcDate { get; }
		System.Guid ReservationRequestId { get; }
		int ReservationRequestOptionId { get; }
		int Score { get; }
		System.DateTime SuggestedPickupEnd { get; }
		System.DateTime SuggestedPickupStart { get; }

		List<IReservation> Reservations { get; }


	}
}
