// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace CGH.QuikRide.Model.QR.Interface
{
	public partial interface IVehicle
	{
		string CreatedBy { get; }
		System.DateTime CreatedUtcDate { get; }
		int DataVersion { get; }
		System.DateTime? EndDateInService { get; }
		bool IsDeleted { get; }
		double? Latitude { get; }
		string LicensePlateNumber { get; }
		double? Longitude { get; }
		string ModifiedBy { get; }
		System.DateTime ModifiedUtcDate { get; }
		System.DateTime StartDateInService { get; }
		int VehicleId { get; }
		int VehicleStatusTypeId { get; }
		int VehicleTypeId { get; }
		string Vin { get; }

		IVehicleStatusType VehicleStatusType { get; }
		IVehicleType VehicleType { get; }
		List<IDriver> Drivers { get; }
		List<IRide> Rides { get; }
		List<IVehicleBusRoute> VehicleBusRoutes { get; }
		List<IVehicleVehicleFeatureType> VehicleVehicleFeatureTypes { get; }


	}
}
