// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace CGH.QuikRide.Model.QR.Interface
{
	public partial interface IVehicleType
	{
		int? Capacity { get; }
		string Code { get; }
		string CreatedBy { get; }
		System.DateTime CreatedUtcDate { get; }
		int DataVersion { get; }
		string Description { get; }
		int DisplayPriority { get; }
		string DisplayText { get; }
		double? FrontOverhangInFeet { get; }
		double? GroundClearanceInFeet { get; }
		double? HeightInFeet { get; }
		bool IsDeleted { get; }
		int LanguageTypeId { get; }
		double? LengthInFeetMax { get; }
		double? LengthInFeetMin { get; }
		double? LengthWithBumpers { get; }
		string ModifiedBy { get; }
		System.DateTime ModifiedUtcDate { get; }
		double? RearOverhangInFeet { get; }
		int VehicleTypeId { get; }
		double? WheelbaseInFeet { get; }
		double? WidthInFeet { get; }
		double? WidthWithMirrorsInFeet { get; }

		ILanguageType LanguageType { get; }
		List<IVehicle> Vehicles { get; }
		List<IVehicleTypeVehicleFeatureType> VehicleTypeVehicleFeatureTypes { get; }


	}
}
