// <auto-generated> - Template:MvvmLightModelObject, Version:1.1, Id:c644a31c-7ebc-4383-bc7f-0ea7c5bf6ed4
using GalaSoft.MvvmLight;

namespace CGH.QuikRide.Xam.ModelObj.QR
{
	public partial class Ride : ObservableObject
	{
		public Ride()
		{
			RidePositions = new System.Collections.Generic.List<RidePosition>(); // Reverse Navigation

			InitializePartial();
		}

		private string _createdBy;
		private System.DateTime _createdUtcDate;
		private int _dataVersion;
		private int _driverId;
		private int? _durationInSeconds;
		private System.DateTime? _end;
		private double? _endLatitude;
		private double? _endLongitude;
		private int? _geoDistance;
		private bool _isDeleted;
		private string _modifiedBy;
		private System.DateTime _modifiedUtcDate;
		private System.Guid _rideId;
		private System.DateTime? _start;
		private double? _startLatitude;
		private double? _startLongitude;
		private int _userId;
		private int _vehicleId;


		public string CreatedBy
		{
			get { return _createdBy; }
			set
			{
				Set<string>(() => CreatedBy, ref _createdBy, value);
				RunCustomLogicSetCreatedBy(value);
			}
		}

		public System.DateTime CreatedUtcDate
		{
			get { return _createdUtcDate; }
			set
			{
				Set<System.DateTime>(() => CreatedUtcDate, ref _createdUtcDate, value);
				RunCustomLogicSetCreatedUtcDate(value);
			}
		}

		public int DataVersion
		{
			get { return _dataVersion; }
			set
			{
				Set<int>(() => DataVersion, ref _dataVersion, value);
				RunCustomLogicSetDataVersion(value);
			}
		}

		public int DriverId
		{
			get { return _driverId; }
			set
			{
				Set<int>(() => DriverId, ref _driverId, value);
				RunCustomLogicSetDriverId(value);
			}
		}

		public int? DurationInSeconds
		{
			get { return _durationInSeconds; }
			set
			{
				Set<int?>(() => DurationInSeconds, ref _durationInSeconds, value);
				RunCustomLogicSetDurationInSeconds(value);
			}
		}

		public System.DateTime? End
		{
			get { return _end; }
			set
			{
				Set<System.DateTime?>(() => End, ref _end, value);
				RunCustomLogicSetEnd(value);
			}
		}

		public double? EndLatitude
		{
			get { return _endLatitude; }
			set
			{
				Set<double?>(() => EndLatitude, ref _endLatitude, value);
				RunCustomLogicSetEndLatitude(value);
			}
		}

		public double? EndLongitude
		{
			get { return _endLongitude; }
			set
			{
				Set<double?>(() => EndLongitude, ref _endLongitude, value);
				RunCustomLogicSetEndLongitude(value);
			}
		}

		public int? GeoDistance
		{
			get { return _geoDistance; }
			set
			{
				Set<int?>(() => GeoDistance, ref _geoDistance, value);
				RunCustomLogicSetGeoDistance(value);
			}
		}

		public bool IsDeleted
		{
			get { return _isDeleted; }
			set
			{
				Set<bool>(() => IsDeleted, ref _isDeleted, value);
				RunCustomLogicSetIsDeleted(value);
			}
		}

		public string ModifiedBy
		{
			get { return _modifiedBy; }
			set
			{
				Set<string>(() => ModifiedBy, ref _modifiedBy, value);
				RunCustomLogicSetModifiedBy(value);
			}
		}

		public System.DateTime ModifiedUtcDate
		{
			get { return _modifiedUtcDate; }
			set
			{
				Set<System.DateTime>(() => ModifiedUtcDate, ref _modifiedUtcDate, value);
				RunCustomLogicSetModifiedUtcDate(value);
			}
		}

		public System.Guid RideId
		{
			get { return _rideId; }
			set
			{
				Set<System.Guid>(() => RideId, ref _rideId, value);
				RunCustomLogicSetRideId(value);
			}
		}

		public System.DateTime? Start
		{
			get { return _start; }
			set
			{
				Set<System.DateTime?>(() => Start, ref _start, value);
				RunCustomLogicSetStart(value);
			}
		}

		public double? StartLatitude
		{
			get { return _startLatitude; }
			set
			{
				Set<double?>(() => StartLatitude, ref _startLatitude, value);
				RunCustomLogicSetStartLatitude(value);
			}
		}

		public double? StartLongitude
		{
			get { return _startLongitude; }
			set
			{
				Set<double?>(() => StartLongitude, ref _startLongitude, value);
				RunCustomLogicSetStartLongitude(value);
			}
		}

		public int UserId
		{
			get { return _userId; }
			set
			{
				Set<int>(() => UserId, ref _userId, value);
				RunCustomLogicSetUserId(value);
			}
		}

		public int VehicleId
		{
			get { return _vehicleId; }
			set
			{
				Set<int>(() => VehicleId, ref _vehicleId, value);
				RunCustomLogicSetVehicleId(value);
			}
		}

		public virtual System.Collections.Generic.IList<RidePosition> RidePositions { get; set; } // Many to many mapping
		public virtual Driver Driver { get; set; } 
		public virtual User User { get; set; } 
		public virtual Vehicle Vehicle { get; set; } 


		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetCreatedBy(string value);
		partial void RunCustomLogicSetCreatedUtcDate(System.DateTime value);
		partial void RunCustomLogicSetDataVersion(int value);
		partial void RunCustomLogicSetDriverId(int value);
		partial void RunCustomLogicSetDurationInSeconds(int? value);
		partial void RunCustomLogicSetEnd(System.DateTime? value);
		partial void RunCustomLogicSetEndLatitude(double? value);
		partial void RunCustomLogicSetEndLongitude(double? value);
		partial void RunCustomLogicSetGeoDistance(int? value);
		partial void RunCustomLogicSetIsDeleted(bool value);
		partial void RunCustomLogicSetModifiedBy(string value);
		partial void RunCustomLogicSetModifiedUtcDate(System.DateTime value);
		partial void RunCustomLogicSetRideId(System.Guid value);
		partial void RunCustomLogicSetStart(System.DateTime? value);
		partial void RunCustomLogicSetStartLatitude(double? value);
		partial void RunCustomLogicSetStartLongitude(double? value);
		partial void RunCustomLogicSetUserId(int value);
		partial void RunCustomLogicSetVehicleId(int value);

		#endregion RunCustomLogicSet

	}
}
